package Database

import "github.com/Darklabel91/LegalDoc_Classifier/Structs"

func DataSetCNJDocument() []Structs.DocumentCNJ {
	var DocumentCNJ []Structs.DocumentCNJ
	DocumentCNJ = append(DocumentCNJ,
		//Structs.DocumentCNJ{"cod_item", "cod_item_pai", "nome"},
		Structs.DocumentCNJ{"1", "NULL", "Externos"},
		Structs.DocumentCNJ{"2", "NULL", "Internos"},
		Structs.DocumentCNJ{"3", "1", "Ações processuais"},
		Structs.DocumentCNJ{"4", "1", "Elementos de prova"},
		Structs.DocumentCNJ{"5", "1", "Manifestações"},
		Structs.DocumentCNJ{"6", "1", "Peça Informativa"},
		Structs.DocumentCNJ{"7", "3", "Aditamento"},
		Structs.DocumentCNJ{"8", "3", "Alegações Finais"},
		Structs.DocumentCNJ{"9", "3", "Alvará"},
		Structs.DocumentCNJ{"11", "3", "Acordo"},
		Structs.DocumentCNJ{"12", "3", "Auto de Prisão em Flagrante Delito"},
		Structs.DocumentCNJ{"13", "3", "Balanço Patrimonial"},
		Structs.DocumentCNJ{"14", "3", "Carta"},
		Structs.DocumentCNJ{"15", "3", "Ciência"},
		Structs.DocumentCNJ{"16", "3", "Contestação"},
		Structs.DocumentCNJ{"17", "3", "Contraminuta"},
		Structs.DocumentCNJ{"18", "3", "Contrarrazões"},
		Structs.DocumentCNJ{"19", "3", "Defesa Prévia"},
		Structs.DocumentCNJ{"20", "3", "Denúncia"},
		Structs.DocumentCNJ{"21", "3", "Dissidência Partidária"},
		Structs.DocumentCNJ{"22", "3", "Documentos Diversos"},
		Structs.DocumentCNJ{"23", "3", "Emenda à Inicial"},
		Structs.DocumentCNJ{"24", "3", "Exceção"},
		Structs.DocumentCNJ{"25", "3", "Execução/Cumprimento de Sentença"},
		Structs.DocumentCNJ{"26", "3", "Impugnação"},
		Structs.DocumentCNJ{"27", "4", "Alvará"},
		Structs.DocumentCNJ{"28", "3", "Incidente"},
		Structs.DocumentCNJ{"29", "3", "Informações Prestadas"},
		Structs.DocumentCNJ{"30", "3", "Inquérito Policial"},
		Structs.DocumentCNJ{"31", "3", "Manifestação"},
		Structs.DocumentCNJ{"32", "3", "Memoriais"},
		Structs.DocumentCNJ{"33", "3", "Notícia de Inelegibilidade"},
		Structs.DocumentCNJ{"34", "3", "Outras Peças"},
		Structs.DocumentCNJ{"35", "3", "Parecer da Procuradoria"},
		Structs.DocumentCNJ{"36", "3", "Pedido"},
		Structs.DocumentCNJ{"37", "3", "Petição"},
		Structs.DocumentCNJ{"39", "3", "Promoção MP/Pedido de Arquivamento"},
		Structs.DocumentCNJ{"40", "3", "Proposta de Acordo"},
		Structs.DocumentCNJ{"41", "3", "Proposta de Governo"},
		Structs.DocumentCNJ{"42", "3", "Quadro Resumo do Pedido"},
		Structs.DocumentCNJ{"43", "3", "Queixa"},
		Structs.DocumentCNJ{"44", "3", "Questionamento da Distribuição"},
		Structs.DocumentCNJ{"45", "3", "Razões"},
		Structs.DocumentCNJ{"46", "3", "Reconvenção"},
		Structs.DocumentCNJ{"47", "3", "Resposta"},
		Structs.DocumentCNJ{"48", "3", "Recurso"},
		Structs.DocumentCNJ{"49", "3", "Réplica"},
		Structs.DocumentCNJ{"50", "3", "Renúncia"},
		Structs.DocumentCNJ{"51", "3", "Solicitação de Honorários de Perito"},
		Structs.DocumentCNJ{"52", "3", "Tréplica"},
		Structs.DocumentCNJ{"53", "3", "Tutela Provisória Incidental"},
		Structs.DocumentCNJ{"54", "7", "Aditamento à Denúncia"},
		Structs.DocumentCNJ{"55", "4", "Assentamento Individual/Extrato de Registros Funcionais"},
		Structs.DocumentCNJ{"56", "4", "Auto"},
		Structs.DocumentCNJ{"57", "4", "Atestado"},
		Structs.DocumentCNJ{"58", "4", "Ato Impugnado"},
		Structs.DocumentCNJ{"59", "4", "Atos Constitutivos da Pessoa Jurídica"},
		Structs.DocumentCNJ{"60", "4", "Aviso de Recebimento - AR"},
		Structs.DocumentCNJ{"61", "4", "Sisbajud"},
		Structs.DocumentCNJ{"62", "4", "Cálculo"},
		Structs.DocumentCNJ{"63", "4", "Carta"},
		Structs.DocumentCNJ{"64", "4", "Carteira de Habilitação"},
		Structs.DocumentCNJ{"65", "4", "Cédula de Identidade"},
		Structs.DocumentCNJ{"66", "4", "Certidão"},
		Structs.DocumentCNJ{"67", "4", "Cessão"},
		Structs.DocumentCNJ{"68", "4", "Certificado de Compensação"},
		Structs.DocumentCNJ{"69", "4", "CPF/CNPJ"},
		Structs.DocumentCNJ{"70", "4", "Comprovante"},
		Structs.DocumentCNJ{"72", "4", "Conta"},
		Structs.DocumentCNJ{"73", "4", "Contrato"},
		Structs.DocumentCNJ{"74", "4", "Controle de Ponto/Horário de Trabalho"},
		Structs.DocumentCNJ{"75", "4", "Convenção/Acordo Coletiva de Trabalho"},
		Structs.DocumentCNJ{"76", "4", "Cópias Extraídas de Outros Processos"},
		Structs.DocumentCNJ{"77", "4", "Cota"},
		Structs.DocumentCNJ{"78", "4", "Custas Judiciais"},
		Structs.DocumentCNJ{"79", "4", "Declaração de Hipossuficiência"},
		Structs.DocumentCNJ{"80", "4", "Demonstrativo"},
		Structs.DocumentCNJ{"82", "4", "Depósito Judicial"},
		Structs.DocumentCNJ{"83", "4", "Documento de Perito"},
		Structs.DocumentCNJ{"84", "4", "Documentos Sigilosos"},
		Structs.DocumentCNJ{"85", "4", "E-mail"},
		Structs.DocumentCNJ{"86", "4", "Escritura"},
		Structs.DocumentCNJ{"87", "4", "Estudo Psicossocial"},
		Structs.DocumentCNJ{"88", "4", "Estudo Social"},
		Structs.DocumentCNJ{"89", "4", "Exame Médico"},
		Structs.DocumentCNJ{"90", "4", "Extrato"},
		Structs.DocumentCNJ{"91", "4", "Ficha"},
		Structs.DocumentCNJ{"92", "4", "Fotografia"},
		Structs.DocumentCNJ{"93", "4", "Frequência"},
		Structs.DocumentCNJ{"94", "4", "Guia"},
		Structs.DocumentCNJ{"95", "4", "Imposto de Renda"},
		Structs.DocumentCNJ{"96", "4", "INFOJUD"},
		Structs.DocumentCNJ{"97", "4", "Informação Prisional"},
		Structs.DocumentCNJ{"98", "4", "Informações da Autoridade Impetrada"},
		Structs.DocumentCNJ{"99", "4", "Instrumento de Procuração"},
		Structs.DocumentCNJ{"100", "4", "Laudo"},
		Structs.DocumentCNJ{"101", "4", "Manifestação"},
		Structs.DocumentCNJ{"102", "4", "Nota Técnica"},
		Structs.DocumentCNJ{"103", "4", "Notificação"},
		Structs.DocumentCNJ{"104", "4", "Ofício"},
		Structs.DocumentCNJ{"105", "4", "Orçamento"},
		Structs.DocumentCNJ{"106", "4", "Outros Documentos"},
		Structs.DocumentCNJ{"107", "4", "Parecer"},
		Structs.DocumentCNJ{"108", "4", "Perícia"},
		Structs.DocumentCNJ{"109", "4", "Passaporte"},
		Structs.DocumentCNJ{"110", "4", "Planilha de Cálculo"},
		Structs.DocumentCNJ{"111", "4", "Planta/Mapa"},
		Structs.DocumentCNJ{"112", "4", "Porte de Remessa e Retorno"},
		Structs.DocumentCNJ{"113", "4", "Programa"},
		Structs.DocumentCNJ{"114", "4", "Prova Emprestada"},
		Structs.DocumentCNJ{"115", "4", "Recibo"},
		Structs.DocumentCNJ{"117", "4", "Registro Funcional"},
		Structs.DocumentCNJ{"118", "4", "Relatório"},
		Structs.DocumentCNJ{"120", "4", "Resposta de Ofício"},
		Structs.DocumentCNJ{"121", "4", "RENAJUD"},
		Structs.DocumentCNJ{"122", "4", "SERASAJUD"},
		Structs.DocumentCNJ{"123", "4", "SIEL"},
		Structs.DocumentCNJ{"124", "4", "Título"},
		Structs.DocumentCNJ{"125", "5", "Ciência"},
		Structs.DocumentCNJ{"126", "5", "Cota"},
		Structs.DocumentCNJ{"128", "5", "Manifestação (Outras)"},
		Structs.DocumentCNJ{"129", "5", "Requerimento de Liberdade"},
		Structs.DocumentCNJ{"130", "5", "Requerimento de Prisão"},
		Structs.DocumentCNJ{"131", "5", "Requisição de Mandado de Pagamento"},
		Structs.DocumentCNJ{"132", "6", "Aditamento de Registro de Ocorrência"},
		Structs.DocumentCNJ{"133", "6", "Auto de Apreensão e Entrega"},
		Structs.DocumentCNJ{"134", "6", "Peça de Informação"},
		Structs.DocumentCNJ{"135", "6", "Prisão em Flagrante"},
		Structs.DocumentCNJ{"136", "6", "Registro de Ocorrência"},
		Structs.DocumentCNJ{"138", "7", "Aditamento à Inicial"},
		Structs.DocumentCNJ{"139", "7", "Aditamento (Outros)"},
		Structs.DocumentCNJ{"140", "3", "Assistência Litisconsorcial"},
		Structs.DocumentCNJ{"142", "11", "Acordo de Não-Persecução Penal"},
		Structs.DocumentCNJ{"143", "11", "Acordo (Outros)"},
		Structs.DocumentCNJ{"144", "14", "Carta Arbitral"},
		Structs.DocumentCNJ{"145", "14", "Carta de Concessão"},
		Structs.DocumentCNJ{"146", "14", "Carta de Indeferimento"},
		Structs.DocumentCNJ{"147", "14", "Carta de Ordem"},
		Structs.DocumentCNJ{"148", "14", "Carta Precatória"},
		Structs.DocumentCNJ{"149", "20", "Abuso de Autoridade"},
		Structs.DocumentCNJ{"150", "20", "Abuso de Poder Econômico"},
		Structs.DocumentCNJ{"151", "20", "Crime Eleitoral"},
		Structs.DocumentCNJ{"152", "20", "Conduta Vedada Agente Público"},
		Structs.DocumentCNJ{"153", "20", "Denúncia (Outras)"},
		Structs.DocumentCNJ{"154", "20", "Noticia Inelegibilidade/Condição de Elegibilidade"},
		Structs.DocumentCNJ{"155", "24", "Exceção de Coisa Julgada"},
		Structs.DocumentCNJ{"156", "24", "Exceção de Impedimento"},
		Structs.DocumentCNJ{"157", "24", "Exceção de Incompetência"},
		Structs.DocumentCNJ{"158", "24", "Exceção de Litispendência"},
		Structs.DocumentCNJ{"159", "24", "Exceção de Pré-Executividade"},
		Structs.DocumentCNJ{"160", "24", "Exceção de Suspeição"},
		Structs.DocumentCNJ{"161", "25", "Execução Definitiva/Cumprimento Definitivo de Sentença"},
		Structs.DocumentCNJ{"162", "25", "Execução Provisória/Cumprimento Provisório de Sentença"},
		Structs.DocumentCNJ{"163", "26", "Impugnação à Execução"},
		Structs.DocumentCNJ{"164", "26", "Impugnação ao Cumprimento de Sentença"},
		Structs.DocumentCNJ{"165", "26", "Impugnação aos Cálculos"},
		Structs.DocumentCNJ{"166", "26", "Impugnação aos Embargos"},
		Structs.DocumentCNJ{"167", "28", "IAC"},
		Structs.DocumentCNJ{"168", "28", "Incidente de Dependência Toxicológica"},
		Structs.DocumentCNJ{"169", "28", "Incidente de Insanidade"},
		Structs.DocumentCNJ{"170", "28", "Incidente de Perícia de Voz"},
		Structs.DocumentCNJ{"171", "28", "Incidente de Uniformização de Jurisprudência"},
		Structs.DocumentCNJ{"172", "28", "Incidente (Outros)"},
		Structs.DocumentCNJ{"173", "28", "IRDR"},
		Structs.DocumentCNJ{"174", "29", "Informações da Autoridade Impetrada"},
		Structs.DocumentCNJ{"175", "31", "Manifestação de Desinteresse na Autocomposição (art. 334 CPC)"},
		Structs.DocumentCNJ{"176", "31", "Manifestação - Dilação de Prazo Deferida"},
		Structs.DocumentCNJ{"177", "31", "Manifestação - Dilação de Prazo Indeferida"},
		Structs.DocumentCNJ{"178", "31", "Manifestação da AGU"},
		Structs.DocumentCNJ{"179", "31", "Manifestação do Ministério Público"},
		Structs.DocumentCNJ{"180", "31", "Manifestação (Outras)"},
		Structs.DocumentCNJ{"181", "36", "Pedido Contraposto"},
		Structs.DocumentCNJ{"182", "36", "Pedido de Arquivamento"},
		Structs.DocumentCNJ{"183", "36", "Pedido de Assistência jurídica"},
		Structs.DocumentCNJ{"184", "36", "Pedido de Desarquivamento"},
		Structs.DocumentCNJ{"185", "36", "Pedido de Desistência"},
		Structs.DocumentCNJ{"187", "36", "Pedido de Extinção do Processo"},
		Structs.DocumentCNJ{"188", "36", "Pedido de Gratuidade de Justiça"},
		Structs.DocumentCNJ{"189", "36", "Pedido de Habilitação"},
		Structs.DocumentCNJ{"190", "36", "Pedido de Homologação de acordo"},
		Structs.DocumentCNJ{"191", "36", "Pedido de liberdade provisória"},
		Structs.DocumentCNJ{"192", "36", "Pedido de liminar/antecipação de tutela"},
		Structs.DocumentCNJ{"193", "36", "Pedido de prioridade de tramitação"},
		Structs.DocumentCNJ{"194", "36", "Pedido de reconsideração de decisão"},
		Structs.DocumentCNJ{"195", "36", "Pedido de retirada de pauta"},
		Structs.DocumentCNJ{"196", "36", "Pedido de suspensão condicional do processo"},
		Structs.DocumentCNJ{"197", "36", "Pedido de suspensão do processo"},
		Structs.DocumentCNJ{"198", "36", "Pedido de transação penal"},
		Structs.DocumentCNJ{"199", "36", "Pedido de Uniformização de Interpretação de Lei Federal"},
		Structs.DocumentCNJ{"201", "37", "Petição de Habilitação"},
		Structs.DocumentCNJ{"202", "37", "Petição Inicial"},
		Structs.DocumentCNJ{"207", "37", "Petição Intercorrente"},
		Structs.DocumentCNJ{"208", "37", "Petição Intermediária"},
		Structs.DocumentCNJ{"209", "37", "Petição (Outras)"},
		Structs.DocumentCNJ{"210", "37", "Petição Requerendo"},
		Structs.DocumentCNJ{"211", "37", "Petição Simples de Terceiro Interessado"},
		Structs.DocumentCNJ{"212", "47", "Resposta à Acusação"},
		Structs.DocumentCNJ{"213", "47", "Resposta a Recurso"},
		Structs.DocumentCNJ{"214", "48", "Recurso Administrativo"},
		Structs.DocumentCNJ{"215", "48", "Adesivo"},
		Structs.DocumentCNJ{"216", "48", "Agravo"},
		Structs.DocumentCNJ{"225", "48", "Apelação"},
		Structs.DocumentCNJ{"226", "48", "Correição Parcial"},
		Structs.DocumentCNJ{"227", "48", "Embargos"},
		Structs.DocumentCNJ{"232", "48", "Recurso Criminal Eleitoral"},
		Structs.DocumentCNJ{"233", "48", "Recurso de Revista"},
		Structs.DocumentCNJ{"234", "48", "Recurso Eleitoral"},
		Structs.DocumentCNJ{"235", "48", "Recurso em Direito de Resposta"},
		Structs.DocumentCNJ{"236", "48", "Recurso em Reclamação"},
		Structs.DocumentCNJ{"237", "48", "Recurso em Representação"},
		Structs.DocumentCNJ{"238", "48", "Recurso em Sentido Estrito"},
		Structs.DocumentCNJ{"239", "48", "Recurso Especial"},
		Structs.DocumentCNJ{"240", "48", "Recurso Especial Eleitoral"},
		Structs.DocumentCNJ{"241", "48", "Recurso Extraordinário"},
		Structs.DocumentCNJ{"242", "48", "Recurso Inominado"},
		Structs.DocumentCNJ{"243", "48", "Recurso Ordinário"},
		Structs.DocumentCNJ{"244", "50", "Renúncia de Mandato"},
		Structs.DocumentCNJ{"245", "50", "Renúncia de Prazo"},
		Structs.DocumentCNJ{"247", "47", "Resposta Preliminar"},
		Structs.DocumentCNJ{"248", "27", "Alvará de Construção"},
		Structs.DocumentCNJ{"249", "27", "Alvará de Funcionamento"},
		Structs.DocumentCNJ{"251", "56", "Auto de Colheita de Material Gráfico"},
		Structs.DocumentCNJ{"252", "56", "Auto de Depósito"},
		Structs.DocumentCNJ{"253", "56", "Auto de Exibição/Apreensão/Entrega"},
		Structs.DocumentCNJ{"254", "56", "Auto de Reconhecimento"},
		Structs.DocumentCNJ{"255", "57", "Atestado de Comparecimento"},
		Structs.DocumentCNJ{"256", "57", "Atestado de Óbito"},
		Structs.DocumentCNJ{"257", "57", "Atestado de Saúde"},
		Structs.DocumentCNJ{"258", "62", "Cálculo do Executado"},
		Structs.DocumentCNJ{"259", "62", "Cálculo de Pena"},
		Structs.DocumentCNJ{"260", "62", "Cálculo de Alimentos"},
		Structs.DocumentCNJ{"261", "62", "Cálculo de Acidente de Trabalho"},
		Structs.DocumentCNJ{"262", "63", "Carta de Preposto"},
		Structs.DocumentCNJ{"263", "63", "Carta (Outras)"},
		Structs.DocumentCNJ{"264", "66", "Certidão de Comportamento"},
		Structs.DocumentCNJ{"265", "66", "Certidão de Dívida Ativa"},
		Structs.DocumentCNJ{"266", "66", "Certidão de Objeto e Pé"},
		Structs.DocumentCNJ{"267", "66", "Certidão de Óbito"},
		Structs.DocumentCNJ{"268", "66", "Certidão de Oficial de Justiça"},
		Structs.DocumentCNJ{"269", "66", "Certidão de Protesto"},
		Structs.DocumentCNJ{"270", "66", "Certidão de Registro Imobiliário"},
		Structs.DocumentCNJ{"271", "66", "Certidão de Venda"},
		Structs.DocumentCNJ{"272", "66", "Certidão Pública da Justiça"},
		Structs.DocumentCNJ{"273", "67", "Cessão de Direito de Bem Móvel"},
		Structs.DocumentCNJ{"274", "67", "Cessão de Direito de Bem Imóvel"},
		Structs.DocumentCNJ{"275", "67", "Cessão (Outros)"},
		Structs.DocumentCNJ{"276", "70", "Comprovante de AR"},
		Structs.DocumentCNJ{"277", "70", "Comprovante de Endereço"},
		Structs.DocumentCNJ{"278", "70", "Comprovante de Imposto de Renda"},
		Structs.DocumentCNJ{"279", "70", "Comprovante de Suspensão de Prazo"},
		Structs.DocumentCNJ{"280", "70", "Comprovante de Rendimento"},
		Structs.DocumentCNJ{"282", "70", "Comprovante de Trabalho"},
		Structs.DocumentCNJ{"283", "70", "Comprovante de cadastro de advogado"},
		Structs.DocumentCNJ{"284", "70", "Comprovante de cadastro de jus postulandi"},
		Structs.DocumentCNJ{"285", "70", "Comprovante de desincompatibilização"},
		Structs.DocumentCNJ{"286", "70", "Comprovante de escolaridade"},
		Structs.DocumentCNJ{"287", "72", "Conta de Água"},
		Structs.DocumentCNJ{"288", "72", "Conta de Energia"},
		Structs.DocumentCNJ{"289", "72", "Conta de Telefone"},
		Structs.DocumentCNJ{"290", "73", "Contrato de Trabalho"},
		Structs.DocumentCNJ{"292", "73", "Contrato (Outros)"},
		Structs.DocumentCNJ{"293", "73", "Contrato Social"},
		Structs.DocumentCNJ{"294", "80", "Demonstrativo de Cálculo"},
		Structs.DocumentCNJ{"295", "80", "Demonstrativo do Repasse do Valor da Parcela"},
		Structs.DocumentCNJ{"296", "83", "Declaração de não comparecimento à perícia médica"},
		Structs.DocumentCNJ{"297", "83", "Esclarecimento de Perito"},
		Structs.DocumentCNJ{"298", "90", "Extrato Bancário"},
		Structs.DocumentCNJ{"299", "90", "Extrato de FGTS"},
		Structs.DocumentCNJ{"300", "91", "Ficha Financeira"},
		Structs.DocumentCNJ{"301", "91", "Ficha de Registro de Empregado"},
		Structs.DocumentCNJ{"302", "94", "Guia de Depósito Judicial"},
		Structs.DocumentCNJ{"303", "94", "Guia de Recolhimento"},
		Structs.DocumentCNJ{"304", "99", "Autor/Recorrente"},
		Structs.DocumentCNJ{"305", "99", "Réu/Recorrido"},
		Structs.DocumentCNJ{"306", "99", "Substabelecimento do Autor/Recorrente"},
		Structs.DocumentCNJ{"308", "99", "Substabelecimento do Réu/Recorrido"},
		Structs.DocumentCNJ{"310", "99", "Terceiro/Interessado"},
		Structs.DocumentCNJ{"311", "100", "Laudo de Avaliação"},
		Structs.DocumentCNJ{"312", "100", "Laudo de Exame"},
		Structs.DocumentCNJ{"313", "100", "Laudo de Perícia"},
		Structs.DocumentCNJ{"314", "100", "Laudo dos Assistentes Técnicos"},
		Structs.DocumentCNJ{"315", "100", "Laudo (Outros)"},
		Structs.DocumentCNJ{"316", "104", "Ofício (Outros)"},
		Structs.DocumentCNJ{"317", "104", "Ofício Requisitório de Precatório"},
		Structs.DocumentCNJ{"318", "107", "Parecer do MP"},
		Structs.DocumentCNJ{"319", "107", "Parecer (Outros)"},
		Structs.DocumentCNJ{"320", "107", "Parecer Técnico"},
		Structs.DocumentCNJ{"321", "113", "Programa de Controle Médico de Saúde Ocupacional (PCMSO)"},
		Structs.DocumentCNJ{"322", "113", "Programa de Formação do Patrimônio do Servidor Público (PASEP)"},
		Structs.DocumentCNJ{"323", "113", "Programa de Integração Social (PIS)"},
		Structs.DocumentCNJ{"324", "113", "Programa de Prevenção de Riscos Ambientais (PPRA)"},
		Structs.DocumentCNJ{"326", "115", "Recibo de Entrega de Equipamento de Proteção Individual (EPI)"},
		Structs.DocumentCNJ{"327", "115", "Recibo de Entrega de Uniforme"},
		Structs.DocumentCNJ{"328", "115", "Recibo de Entrega de Vale Refeição"},
		Structs.DocumentCNJ{"329", "115", "Recibo de Entrega de Vale Transporte"},
		Structs.DocumentCNJ{"330", "115", "Recibo de Envio ao BNMP"},
		Structs.DocumentCNJ{"331", "115", "Recibo de Férias"},
		Structs.DocumentCNJ{"332", "115", "Recibo (Outros)"},
		Structs.DocumentCNJ{"334", "118", "Relatório de Acompanhamento"},
		Structs.DocumentCNJ{"337", "118", "Relatório de Comparecimento - Medida Socioeducativa"},
		Structs.DocumentCNJ{"338", "118", "Relatório de Encerramento"},
		Structs.DocumentCNJ{"341", "118", "Relatório Informativo"},
		Structs.DocumentCNJ{"342", "118", "Relatório Inicial - PIA"},
		Structs.DocumentCNJ{"345", "118", "Relatório Psicológico"},
		Structs.DocumentCNJ{"346", "118", "Relatório Social"},
		Structs.DocumentCNJ{"347", "124", "Título Extrajudicial"},
		Structs.DocumentCNJ{"348", "124", "Título Judicial"},
		Structs.DocumentCNJ{"349", "124", "Título (Outros)"},
		Structs.DocumentCNJ{"351", "126", "Cota Ministerial"},
		Structs.DocumentCNJ{"352", "126", "Cota (Outras)"},
		Structs.DocumentCNJ{"353", "140", "Denunciação da Lide"},
		Structs.DocumentCNJ{"354", "140", "Assistência Litisconsorcial (Outras)"},
		Structs.DocumentCNJ{"355", "185", "Pedido de Desistência da Ação "},
		Structs.DocumentCNJ{"356", "185", "Pedido de Desistência do Recurso "},
		Structs.DocumentCNJ{"357", "199", "Pedido de uniformização de interpretação de lei federal - Nacional "},
		Structs.DocumentCNJ{"358", "199", "Pedido de uniformização de interpretação de lei federal - Regional "},
		Structs.DocumentCNJ{"359", "202", "Petição Inicial com Pedido de Busca e Apreensão "},
		Structs.DocumentCNJ{"360", "202", "Petição Inicial com Pedido de Cassação "},
		Structs.DocumentCNJ{"361", "202", "Petição Inicial com Pedido de Sigilo "},
		Structs.DocumentCNJ{"362", "202", "Petição Inicial com Pedido Liminar/Antecipação de Tutela "},
		Structs.DocumentCNJ{"363", "202", "Petição Inicial (Outras) "},
		Structs.DocumentCNJ{"364", "216", "Agravo Inominado ou Legal "},
		Structs.DocumentCNJ{"365", "216", "Agravo de Instrumento "},
		Structs.DocumentCNJ{"366", "216", "Agravo em Pedido de Uniformização de Interpretação de Lei Federal "},
		Structs.DocumentCNJ{"367", "216", "Agravo em Recurso Especial "},
		Structs.DocumentCNJ{"368", "216", "Agravo em Recurso Extraordinário "},
		Structs.DocumentCNJ{"369", "216", "Agravo em Recurso Ordinário "},
		Structs.DocumentCNJ{"370", "216", "Agravo Interno "},
		Structs.DocumentCNJ{"371", "216", "Agravo Regimental "},
		Structs.DocumentCNJ{"372", "216", "Agravo Retido "},
		Structs.DocumentCNJ{"373", "227", "Embargos de Declaração "},
		Structs.DocumentCNJ{"374", "227", "Embargos de Divergência "},
		Structs.DocumentCNJ{"375", "227", "Embargos em Ação Penal "},
		Structs.DocumentCNJ{"376", "227", "Embargos Infringentes "},
		Structs.DocumentCNJ{"377", "227", "Embargos Infringentes e de Nulidade "},
		Structs.DocumentCNJ{"378", "280", "Comprovante de Rendimento (Outros) "},
		Structs.DocumentCNJ{"379", "280", "Contracheque "},
		Structs.DocumentCNJ{"380", "290", "Contrato de Trabalho de Experiência "},
		Structs.DocumentCNJ{"381", "290", "Contrato de Trabalho (Outros) "},
		Structs.DocumentCNJ{"382", "306", "Substabelecimento do Autor/Recorrente com Reserva "},
		Structs.DocumentCNJ{"383", "306", "Substabelecimento do Autor/Recorrente sem Reserva "},
		Structs.DocumentCNJ{"384", "308", "Substabelecimento do Réu/Recorrido com Reserva "},
		Structs.DocumentCNJ{"385", "308", "Substabelecimento do Réu/Recorrido sem Reserva "},
		Structs.DocumentCNJ{"388", "334", " Relatório de Acompanhamento - PSC "},
		Structs.DocumentCNJ{"393", "342", "Relatório Inicial - PIA - LA "},
		Structs.DocumentCNJ{"394", "342", "Relatório Inicial - PIA - LA - PSC "},
		Structs.DocumentCNJ{"395", "342", "Relatório Inicial - PIA - PSC "},
		Structs.DocumentCNJ{"398", "2", "Alvará"},
		Structs.DocumentCNJ{"399", "2", "Ata"},
		Structs.DocumentCNJ{"400", "2", "Auto"},
		Structs.DocumentCNJ{"401", "2", "Carta"},
		Structs.DocumentCNJ{"402", "2", "Certidão"},
		Structs.DocumentCNJ{"403", "2", "Cópia"},
		Structs.DocumentCNJ{"404", "2", "Decisão"},
		Structs.DocumentCNJ{"405", "2", "Decreto Judiciário"},
		Structs.DocumentCNJ{"406", "2", "Dissidência Partidária"},
		Structs.DocumentCNJ{"407", "2", "Documento de Inconsistência"},
		Structs.DocumentCNJ{"408", "2", "Edital"},
		Structs.DocumentCNJ{"409", "2", "Despacho"},
		Structs.DocumentCNJ{"410", "2", "E-mail"},
		Structs.DocumentCNJ{"411", "2", "Guia"},
		Structs.DocumentCNJ{"412", "2", "Informação"},
		Structs.DocumentCNJ{"413", "2", "Instrução Normativa"},
		Structs.DocumentCNJ{"414", "2", "Malote Digital"},
		Structs.DocumentCNJ{"415", "2", "Mandado"},
		Structs.DocumentCNJ{"416", "2", "Mapa de Documentação"},
		Structs.DocumentCNJ{"417", "2", "Ofício"},
		Structs.DocumentCNJ{"418", "2", "Ordem"},
		Structs.DocumentCNJ{"419", "2", "Pauta de Julgamento"},
		Structs.DocumentCNJ{"420", "2", "Portaria"},
		Structs.DocumentCNJ{"421", "2", "Provimento"},
		Structs.DocumentCNJ{"422", "2", "Relatório"},
		Structs.DocumentCNJ{"423", "2", "Termo"},
		Structs.DocumentCNJ{"424", "2", "Título Judicial"},
		Structs.DocumentCNJ{"427", "4", "Comunicação"},
		Structs.DocumentCNJ{"428", "398", "Alvará de Levantamento"},
		Structs.DocumentCNJ{"429", "398", "Alvará de Liberação"},
		Structs.DocumentCNJ{"430", "398", "Alvará de Pagamento"},
		Structs.DocumentCNJ{"431", "398", "Alvará de Recambiamento"},
		Structs.DocumentCNJ{"432", "398", "Alvará de Sepultamento"},
		Structs.DocumentCNJ{"433", "398", "Alvará de Soltura"},
		Structs.DocumentCNJ{"434", "398", "Alvará de Transferência"},
		Structs.DocumentCNJ{"435", "398", "Alvará de Viagem"},
		Structs.DocumentCNJ{"437", "398", "Alvará (Outros)"},
		Structs.DocumentCNJ{"438", "398", "Alvará para Festa"},
		Structs.DocumentCNJ{"439", "398", "Alvará para Trabalhar"},
		Structs.DocumentCNJ{"440", "399", "Ata de Acompanhamento"},
		Structs.DocumentCNJ{"441", "399", "Ata de Audiência"},
		Structs.DocumentCNJ{"442", "399", "Ata de Distribuição"},
		Structs.DocumentCNJ{"443", "399", "Ata de Inspeção"},
		Structs.DocumentCNJ{"444", "399", "Ata de Julgamento"},
		Structs.DocumentCNJ{"445", "399", "Ata de Sessão"},
		Structs.DocumentCNJ{"446", "400", "Auto de Adjudicação"},
		Structs.DocumentCNJ{"447", "400", "Auto de Arrematação"},
		Structs.DocumentCNJ{"448", "400", "Auto de Arresto"},
		Structs.DocumentCNJ{"449", "400", "Auto de Avaliação"},
		Structs.DocumentCNJ{"450", "400", "Auto de Busca e Apreensão"},
		Structs.DocumentCNJ{"451", "400", "Auto de Constatação"},
		Structs.DocumentCNJ{"452", "400", "Auto de Depósito"},
		Structs.DocumentCNJ{"453", "400", "Auto de Penhora"},
		Structs.DocumentCNJ{"454", "400", "Auto de Restauração de Autos"},
		Structs.DocumentCNJ{"455", "401", "Carta Convite"},
		Structs.DocumentCNJ{"456", "401", "Carta de Adjudicação"},
		Structs.DocumentCNJ{"457", "401", "Carta de Arrematação"},
		Structs.DocumentCNJ{"458", "401", "Carta de Guia"},
		Structs.DocumentCNJ{"459", "401", "Carta de Ordem"},
		Structs.DocumentCNJ{"460", "401", "Carta de Preposto"},
		Structs.DocumentCNJ{"461", "401", "Carta de Sentença"},
		Structs.DocumentCNJ{"462", "401", "Carta (Outras)"},
		Structs.DocumentCNJ{"463", "401", "Carta Precatória"},
		Structs.DocumentCNJ{"464", "401", "Carta Rogatória"},
		Structs.DocumentCNJ{"465", "402", "Certidão de Afastamento"},
		Structs.DocumentCNJ{"466", "402", "Certidão de Alteração de Classe"},
		Structs.DocumentCNJ{"467", "402", "Certidão de Antecedentes Penais"},
		Structs.DocumentCNJ{"468", "402", "Certidão de Apensação"},
		Structs.DocumentCNJ{"469", "402", "Certidão de Arquivamento"},
		Structs.DocumentCNJ{"470", "402", "Certidão de Ausência"},
		Structs.DocumentCNJ{"472", "402", "Certidão de Autos Originais Incompletos"},
		Structs.DocumentCNJ{"473", "402", "Certidão de Autuação"},
		Structs.DocumentCNJ{"474", "402", "Certidão de Baixa"},
		Structs.DocumentCNJ{"475", "402", "Certidão de Cancelamento da Distribuição"},
		Structs.DocumentCNJ{"476", "402", "Certidão de Carimbo Ilegível"},
		Structs.DocumentCNJ{"477", "402", "Certidão de Conclusão"},
		Structs.DocumentCNJ{"478", "402", "Certidão da Contadoria"},
		Structs.DocumentCNJ{"479", "402", "Certidão de Consulta"},
		Structs.DocumentCNJ{"480", "402", "Certidão de Crédito"},
		Structs.DocumentCNJ{"481", "402", "Certidão de Cumprimento de Mandado de Prisão"},
		Structs.DocumentCNJ{"482", "402", "Certidão de Custas"},
		Structs.DocumentCNJ{"483", "402", "Certidão de Decurso de Prazo"},
		Structs.DocumentCNJ{"484", "402", "Certidão de Desconstituição da Penhora"},
		Structs.DocumentCNJ{"485", "402", "Certidão de Desentranhamento"},
		Structs.DocumentCNJ{"486", "402", "Certidão de Devolução de AR"},
		Structs.DocumentCNJ{"487", "402", "Certidão de Devolução dos Autos"},
		Structs.DocumentCNJ{"488", "402", "Certidão de Digitalização"},
		Structs.DocumentCNJ{"489", "402", "Certidão de Distribuição"},
		Structs.DocumentCNJ{"490", "402", "Certidão de Dívida Ativa (CDA)"},
		Structs.DocumentCNJ{"491", "402", "Certidão de Expedição"},
		Structs.DocumentCNJ{"492", "402", "Certidão de Extinção de Punibilidade por Morte"},
		Structs.DocumentCNJ{"493", "402", "Certidão de Falta de Páginas"},
		Structs.DocumentCNJ{"494", "402", "Certidão de Fatos"},
		Structs.DocumentCNJ{"495", "402", "Certidão de Gabinete"},
		Structs.DocumentCNJ{"496", "402", "Certidão de Inclusão"},
		Structs.DocumentCNJ{"497", "402", "Certidão de Inscrição de Penhora"},
		Structs.DocumentCNJ{"498", "402", "Certidão de Inspeção"},
		Structs.DocumentCNJ{"499", "402", "Certidão de Inteiro Teor"},
		Structs.DocumentCNJ{"500", "402", "Certidão de Interposição de Recurso"},
		Structs.DocumentCNJ{"501", "402", "Certidão de Intimação"},
		Structs.DocumentCNJ{"502", "402", "Certidão de Inventariante"},
		Structs.DocumentCNJ{"503", "402", "Certidão de Julgamento"},
		Structs.DocumentCNJ{"504", "402", "Certidão de Juntada"},
		Structs.DocumentCNJ{"505", "402", "Certidão de Militância"},
		Structs.DocumentCNJ{"506", "402", "Certidão de Não Apresentação de Contrarrazões"},
		Structs.DocumentCNJ{"507", "402", "Certidão de Não Interposição de Recurso"},
		Structs.DocumentCNJ{"508", "402", "Certidão de Narrativa/Andamento"},
		Structs.DocumentCNJ{"509", "402", "Certidão de Oficial de Justiça"},
		Structs.DocumentCNJ{"510", "402", "Certidão de Página Ilegível"},
		Structs.DocumentCNJ{"511", "402", "Certidão de Pedido de Assistência Judiciária"},
		Structs.DocumentCNJ{"512", "402", "Certidão de Pedido de Vista"},
		Structs.DocumentCNJ{"513", "402", "Certidão de Penhora no Rosto dos Autos"},
		Structs.DocumentCNJ{"514", "402", "Certidão de Protesto"},
		Structs.DocumentCNJ{"515", "402", "Certidão de Publicação"},
		Structs.DocumentCNJ{"516", "402", "Certidão de Quitação de Precatório/RPV"},
		Structs.DocumentCNJ{"517", "402", "Certidão de Redistribuição"},
		Structs.DocumentCNJ{"518", "402", "Certidão de Reenvio de Autos"},
		Structs.DocumentCNJ{"519", "402", "Certidão de Registro de Impedimento"},
		Structs.DocumentCNJ{"520", "402", "Certidão de Remessa"},
		Structs.DocumentCNJ{"521", "402", "Certidão de Republicação"},
		Structs.DocumentCNJ{"522", "402", "Certidão de Retirada de Pauta"},
		Structs.DocumentCNJ{"523", "402", "Certidão de Retificação"},
		Structs.DocumentCNJ{"524", "402", "Certidão de Suspensão de Direitos Políticos"},
		Structs.DocumentCNJ{"525", "402", "Certidão de Tramitação Física"},
		Structs.DocumentCNJ{"526", "402", "Certidão de Transcurso de Prazo"},
		Structs.DocumentCNJ{"527", "402", "Certidão de Trânsito em Julgado"},
		Structs.DocumentCNJ{"528", "402", "Certidão de Triagem"},
		Structs.DocumentCNJ{"529", "402", "Certidão de Validação de Peças Digitalizadas"},
		Structs.DocumentCNJ{"530", "402", "Certidão de Vista Pessoal"},
		Structs.DocumentCNJ{"531", "402", "Certidão Geral de Curatela"},
		Structs.DocumentCNJ{"532", "402", "Certidão Judicial"},
		Structs.DocumentCNJ{"533", "402", "Certidão Negativa de Débitos Trabalhistas (CNDT)"},
		Structs.DocumentCNJ{"534", "402", "Certidão (Outras)"},
		Structs.DocumentCNJ{"535", "404", "Anulação e Substituição de Títulos ao Portador"},
		Structs.DocumentCNJ{"536", "404", "Acórdão"},
		Structs.DocumentCNJ{"537", "404", "Autorização Judicial"},
		Structs.DocumentCNJ{"538", "404", "Decisão Monocrática Terminativa"},
		Structs.DocumentCNJ{"539", "404", "Declinatória de competência"},
		Structs.DocumentCNJ{"540", "404", "Extinção de Processo"},
		Structs.DocumentCNJ{"541", "404", "Interlocutória"},
		Structs.DocumentCNJ{"542", "404", "Juízo de Admissibilidade"},
		Structs.DocumentCNJ{"543", "404", "Juízo de Retratação"},
		Structs.DocumentCNJ{"544", "404", "Ordem de Habeas Corpus"},
		Structs.DocumentCNJ{"545", "404", "Plano Individual de Atendimento"},
		Structs.DocumentCNJ{"546", "404", "Pronúncia"},
		Structs.DocumentCNJ{"547", "404", "Questão de Ordem"},
		Structs.DocumentCNJ{"548", "404", "Reexame de Matéria Repetitiva"},
		Structs.DocumentCNJ{"549", "404", "Requisição/Solicitação Judicial"},
		Structs.DocumentCNJ{"550", "404", "Sentença"},
		Structs.DocumentCNJ{"551", "405", "Decreto Judiciário de Homologação de Declaração de Vacância"},
		Structs.DocumentCNJ{"552", "405", "Decreto Judiciário de Demissão"},
		Structs.DocumentCNJ{"553", "405", "Decreto Judiciário de Homologação de Extinção de Serviço de Foro Extrajudicial"},
		Structs.DocumentCNJ{"554", "405", "Decreto Judiciário de Homologação de Renúncia"},
		Structs.DocumentCNJ{"555", "405", "Decreto Judiciário de Nomeação"},
		Structs.DocumentCNJ{"556", "405", "Decreto Judiciário de Perda de Delegação"},
		Structs.DocumentCNJ{"557", "405", "Decreto Judiciário de Relotação"},
		Structs.DocumentCNJ{"558", "405", "Decreto Judiciário de Remoção"},
		Structs.DocumentCNJ{"559", "407", "Documento de Inconsistência de Advogado"},
		Structs.DocumentCNJ{"560", "407", "Documento de Inconsistência de Jus Postulandi"},
		Structs.DocumentCNJ{"561", "408", "Edital de Alienação de Ativos"},
		Structs.DocumentCNJ{"562", "408", "Edital de Chamamento"},
		Structs.DocumentCNJ{"563", "408", "Edital de Citação"},
		Structs.DocumentCNJ{"564", "408", "Edital de Convocação de Assembleia de Credores"},
		Structs.DocumentCNJ{"565", "408", "Edital de Decretação de Falência e Relação de Credores"},
		Structs.DocumentCNJ{"566", "408", "Edital de Intimação"},
		Structs.DocumentCNJ{"567", "408", "Edital de Leilão"},
		Structs.DocumentCNJ{"568", "408", "Edital de Notificação"},
		Structs.DocumentCNJ{"569", "408", "Edital (Outros)"},
		Structs.DocumentCNJ{"570", "409", "Certificação do Decurso de Prazo"},
		Structs.DocumentCNJ{"571", "409", "Citação"},
		Structs.DocumentCNJ{"572", "409", "Conversão"},
		Structs.DocumentCNJ{"573", "409", "Despacho de Mero Expediente"},
		Structs.DocumentCNJ{"574", "409", "Inicial da Execução"},
		Structs.DocumentCNJ{"575", "409", "Intimação"},
		Structs.DocumentCNJ{"576", "411", "Guia de Acolhimento de Criança e Adolescente"},
		Structs.DocumentCNJ{"577", "411", "Guia de Atualização de Cálculo"},
		Structs.DocumentCNJ{"578", "411", "Guia de Cálculo"},
		Structs.DocumentCNJ{"579", "411", "Guia de Custas"},
		Structs.DocumentCNJ{"580", "411", "Guia de Depósito Judicial"},
		Structs.DocumentCNJ{"581", "411", "Guia de Execução Penal"},
		Structs.DocumentCNJ{"582", "411", "Guia de Fiança"},
		Structs.DocumentCNJ{"583", "411", "Guia de Multa"},
		Structs.DocumentCNJ{"584", "411", "Guia de Preparo"},
		Structs.DocumentCNJ{"585", "411", "Guia de Recolhimento"},
		Structs.DocumentCNJ{"586", "412", "Informação"},
		Structs.DocumentCNJ{"587", "412", "Informação de candidato"},
		Structs.DocumentCNJ{"588", "412", "Informação de coligação"},
		Structs.DocumentCNJ{"589", "412", "Informação de partido"},
		Structs.DocumentCNJ{"590", "415", "Contramandado"},
		Structs.DocumentCNJ{"591", "415", "Diligência de Carta Precatória"},
		Structs.DocumentCNJ{"592", "415", "Formal de Partilha"},
		Structs.DocumentCNJ{"593", "415", "Mandado de Abrigamento"},
		Structs.DocumentCNJ{"594", "415", "Mandado de Acompanhamento"},
		Structs.DocumentCNJ{"595", "415", "Mandado de Afastamento"},
		Structs.DocumentCNJ{"596", "415", "Mandado de Apresentação de Criança e Adolescente"},
		Structs.DocumentCNJ{"597", "415", "Mandado de Apreensão"},
		Structs.DocumentCNJ{"598", "415", "Mandado de Arrecadação"},
		Structs.DocumentCNJ{"600", "415", "Mandado de Arresto"},
		Structs.DocumentCNJ{"601", "415", "Mandado de Arrolamento"},
		Structs.DocumentCNJ{"602", "415", "Mandado de Atendimento Médico"},
		Structs.DocumentCNJ{"603", "415", "Mandado de Avaliação"},
		Structs.DocumentCNJ{"604", "415", "Mandado de Averbação"},
		Structs.DocumentCNJ{"605", "415", "Mandado de Averiguação"},
		Structs.DocumentCNJ{"606", "415", "Mandado de Busca"},
		Structs.DocumentCNJ{"607", "415", "Mandado de Busca e Apreensão"},
		Structs.DocumentCNJ{"608", "415", "Mandado de Citação"},
		Structs.DocumentCNJ{"609", "415", "Mandado de Comparecimento em Audiência Admonitória"},
		Structs.DocumentCNJ{"610", "415", "Mandado de Complemento de Diligência e Informações"},
		Structs.DocumentCNJ{"611", "415", "Mandado de Condução Coercitiva"},
		Structs.DocumentCNJ{"612", "415", "Mandado de Constatação"},
		Structs.DocumentCNJ{"613", "415", "Mandado de Convocação"},
		Structs.DocumentCNJ{"614", "415", "Mandado de Demarcação"},
		Structs.DocumentCNJ{"615", "415", "Mandado de Depósito"},
		Structs.DocumentCNJ{"616", "415", "Mandado de Desconto de Pensão Alimentícia"},
		Structs.DocumentCNJ{"617", "415", "Mandado de Desinternação"},
		Structs.DocumentCNJ{"618", "415", "Mandado de Desocupação"},
		Structs.DocumentCNJ{"619", "415", "Mandado de Despejo"},
		Structs.DocumentCNJ{"620", "415", "Mandado de Encaminhamento"},
		Structs.DocumentCNJ{"621", "415", "Mandado de Entrega"},
		Structs.DocumentCNJ{"622", "415", "Mandado de Imissão na Posse"},
		Structs.DocumentCNJ{"623", "415", "Mandado de Internação"},
		Structs.DocumentCNJ{"624", "415", "Mandado de Intimação"},
		Structs.DocumentCNJ{"625", "415", "Mandado de Interceptação"},
		Structs.DocumentCNJ{"626", "415", "Mandado de Lacramento"},
		Structs.DocumentCNJ{"627", "415", "Mandado de Manutenção"},
		Structs.DocumentCNJ{"628", "415", "Mandado de Monitoramento Eletrônico"},
		Structs.DocumentCNJ{"629", "415", "Mandado de Notificação"},
		Structs.DocumentCNJ{"630", "415", "Mandado de Ordem"},
		Structs.DocumentCNJ{"631", "415", "Mandado de Pagamento"},
		Structs.DocumentCNJ{"632", "415", "Mandado Penhora"},
		Structs.DocumentCNJ{"633", "415", "Mandado de Prisão"},
		Structs.DocumentCNJ{"634", "415", "Mandado de Recambiamento"},
		Structs.DocumentCNJ{"635", "415", "Mandado de Recolhimento"},
		Structs.DocumentCNJ{"636", "415", "Mandado de Registro"},
		Structs.DocumentCNJ{"637", "415", "Mandado de Reintegração de Posse"},
		Structs.DocumentCNJ{"638", "415", "Mandado de Remoção"},
		Structs.DocumentCNJ{"639", "415", "Mandado de Restituição"},
		Structs.DocumentCNJ{"640", "415", "Mandado de Retificação"},
		Structs.DocumentCNJ{"641", "415", "Mandado de Salvo Conduto"},
		Structs.DocumentCNJ{"642", "415", "Mandado de Sequestro"},
		Structs.DocumentCNJ{"643", "415", "Mandado de Sustação e Protesto"},
		Structs.DocumentCNJ{"644", "415", "Mandado de Transcrição para o Livro"},
		Structs.DocumentCNJ{"645", "415", "Mandado de Verificação"},
		Structs.DocumentCNJ{"646", "415", "Mandado de Vistoria"},
		Structs.DocumentCNJ{"647", "415", "Mandado (Outros)"},
		Structs.DocumentCNJ{"648", "416", "Mapa de documentação de coligação"},
		Structs.DocumentCNJ{"649", "416", "Mapa de documentação de partido"},
		Structs.DocumentCNJ{"650", "417", "Ofício-Circular"},
		Structs.DocumentCNJ{"651", "417", "Ofício Comunicando Decisões"},
		Structs.DocumentCNJ{"652", "417", "Ofício Enviando Acórdão"},
		Structs.DocumentCNJ{"653", "417", "Ofício Enviando Informações"},
		Structs.DocumentCNJ{"654", "417", "Ofício (Outros)"},
		Structs.DocumentCNJ{"655", "417", "Ofício Solicitando Informações"},
		Structs.DocumentCNJ{"656", "417", "Ofício Solicitando Peças"},
		Structs.DocumentCNJ{"657", "418", "Ordem de Desinternação"},
		Structs.DocumentCNJ{"658", "418", "Ordem de Liberação"},
		Structs.DocumentCNJ{"659", "418", "Ordem de Serviço"},
		Structs.DocumentCNJ{"660", "420", "Portaria de Derrogação"},
		Structs.DocumentCNJ{"661", "420", "Portaria de Designação"},
		Structs.DocumentCNJ{"662", "420", "Portaria de Homologação"},
		Structs.DocumentCNJ{"663", "420", "Portaria de Instauração de PAD"},
		Structs.DocumentCNJ{"664", "420", "Portaria de Instauração de Sindicância"},
		Structs.DocumentCNJ{"665", "420", "Portaria de Juramentação"},
		Structs.DocumentCNJ{"666", "420", "Portaria de Retificação"},
		Structs.DocumentCNJ{"667", "420", "Portaria de Revogação"},
		Structs.DocumentCNJ{"668", "420", "Portaria de Suspensão de Expediente"},
		Structs.DocumentCNJ{"669", "422", "Relatório de nome social"},
		Structs.DocumentCNJ{"670", "422", "Relatório de requisitos para registro"},
		Structs.DocumentCNJ{"671", "422", "Relatório conclusivo"},
		Structs.DocumentCNJ{"672", "422", "Relatório (outros)"},
		Structs.DocumentCNJ{"673", "423", "Termo Circunstanciado"},
		Structs.DocumentCNJ{"674", "423", "Termo de Abertura/Encerramento"},
		Structs.DocumentCNJ{"675", "423", "Termo de Acordo"},
		Structs.DocumentCNJ{"676", "423", "Termo de Adjudicação"},
		Structs.DocumentCNJ{"677", "423", "Termo de Ajustamento de Conduta"},
		Structs.DocumentCNJ{"678", "423", "Termo de Aplicação de Penalidade"},
		Structs.DocumentCNJ{"679", "423", "Termo de Apresentação e Apreensão"},
		Structs.DocumentCNJ{"680", "423", "Termo de Arresto"},
		Structs.DocumentCNJ{"681", "423", "Termo de Audiência"},
		Structs.DocumentCNJ{"682", "423", "Termo de Autuação"},
		Structs.DocumentCNJ{"683", "423", "Termo de Caução"},
		Structs.DocumentCNJ{"684", "423", "Termo de Cessão de Direitos Hereditários"},
		Structs.DocumentCNJ{"685", "423", "Termo de Ciência da Sentença e Recurso"},
		Structs.DocumentCNJ{"686", "423", "Termo de Comparecimento"},
		Structs.DocumentCNJ{"687", "423", "Termo de Compensação de Débito Tributário"},
		Structs.DocumentCNJ{"688", "423", "Termo de Compromisso"},
		Structs.DocumentCNJ{"689", "423", "Termo de Conciliação"},
		Structs.DocumentCNJ{"690", "423", "Termo de Curatela"},
		Structs.DocumentCNJ{"691", "423", "Termo de Declaração de Testemunha"},
		Structs.DocumentCNJ{"692", "423", "Termo de Depósito"},
		Structs.DocumentCNJ{"693", "423", "Termo de Desconstituição de Penhora"},
		Structs.DocumentCNJ{"694", "423", "Termo de Encerramento"},
		Structs.DocumentCNJ{"695", "423", "Termo de Fiança"},
		Structs.DocumentCNJ{"696", "423", "Termo de Inventariante"},
		Structs.DocumentCNJ{"697", "423", "Termo de Mediação"},
		Structs.DocumentCNJ{"698", "423", "Termo de Penhora"},
		Structs.DocumentCNJ{"699", "423", "Termo de Publicação"},
		Structs.DocumentCNJ{"700", "423", "Termo de Recusa de Mediação/Conciliação"},
		Structs.DocumentCNJ{"701", "423", "Termo de Remessa"},
		Structs.DocumentCNJ{"702", "423", "Termo de Renúncia de Direitos Hereditários"},
		Structs.DocumentCNJ{"703", "423", "Termo de Rescisão de Contrato de Trabalho"},
		Structs.DocumentCNJ{"704", "423", "Termo de Restituição"},
		Structs.DocumentCNJ{"705", "423", "Termo de Transcrição de Depoimento"},
		Structs.DocumentCNJ{"706", "423", "Termo de Tutela"},
		Structs.DocumentCNJ{"707", "29", "Informações Prestadas (Outras)"},
		Structs.DocumentCNJ{"708", "70", "Comprovante de Depósito"},
		Structs.DocumentCNJ{"709", "708", "Comprovante de Depósito Judicial"},
		Structs.DocumentCNJ{"710", "708", "Comprovante de Depósito Recursal"},
		Structs.DocumentCNJ{"711", "427", "Comunicação de Acidente de trabalho (CAT)"},
		Structs.DocumentCNJ{"712", "427", "Comunicação de Dispensa e Seguro Desemprego"},
		Structs.DocumentCNJ{"713", "428", "Alvará de Levantamento (Outros)"},
		Structs.DocumentCNJ{"714", "428", "Alvará de Levantamento de FGTS"},
		Structs.DocumentCNJ{"715", "428", "Alvará de Levantamento de Valores para Perícia"},
		Structs.DocumentCNJ{"716", "428", "Alvará de Levantamento do INSS"},
		Structs.DocumentCNJ{"717", "429", "Alvará de Liberação (Outros)"},
		Structs.DocumentCNJ{"718", "429", "Alvará de Liberação de Coisa Apreendida"},
		Structs.DocumentCNJ{"719", "430", "Alvará de Pagamento de GRU"},
		Structs.DocumentCNJ{"720", "430", "Alvará de Pagamento de Imposto de Renda de Pessoa Física"},
		Structs.DocumentCNJ{"721", "430", "Alvará de Pagamento do INSS"},
		Structs.DocumentCNJ{"722", "433", "Alvará de Soltura (Outros)"},
		Structs.DocumentCNJ{"723", "433", "Alvará de Soltura com Termo"},
		Structs.DocumentCNJ{"724", "433", "Alvará de Soltura em Execução de Alimentos"},
		Structs.DocumentCNJ{"725", "434", "Alvará de Transferência - Sisbajud"},
		Structs.DocumentCNJ{"726", "434", "Alvará de Transferência - Credor"},
		Structs.DocumentCNJ{"727", "434", "Alvará de Transferência - Imposto de Renda de Pessoa Física"},
		Structs.DocumentCNJ{"728", "434", "Alvará de Transferência (Outros)"},
		Structs.DocumentCNJ{"729", "435", "Alvará de Viagem ao Exterior e/ou Passaporte"},
		Structs.DocumentCNJ{"730", "435", "Alvará de Viagem Nacional"},
		Structs.DocumentCNJ{"731", "441", "Ata de Audiência (Outras)"},
		Structs.DocumentCNJ{"732", "441", "Ata de Audiência Admonitória"},
		Structs.DocumentCNJ{"733", "441", "Ata de Audiência de Acolhimento"},
		Structs.DocumentCNJ{"734", "441", "Ata de Audiência de Apresentação (ECA)"},
		Structs.DocumentCNJ{"735", "441", "Ata de Audiência de Conciliação"},
		Structs.DocumentCNJ{"736", "441", "Ata de Audiência de Custódia"},
		Structs.DocumentCNJ{"737", "441", "Ata de Audiência de Instrução"},
		Structs.DocumentCNJ{"738", "441", "Ata de Audiência de Instrução e Julgamento"},
		Structs.DocumentCNJ{"739", "441", "Ata de Audiência de Julgamento"},
		Structs.DocumentCNJ{"740", "441", "Ata de Audiência de Justificação"},
		Structs.DocumentCNJ{"741", "441", "Ata de Audiência de Mediação"},
		Structs.DocumentCNJ{"742", "441", "Ata de Audiência do Art.16 da Lei Maria da Penha"},
		Structs.DocumentCNJ{"743", "445", "Ata de Sessão Extraordinária"},
		Structs.DocumentCNJ{"744", "445", "Ata de Sessão Ordinária"},
		Structs.DocumentCNJ{"745", "463", "Carta Precatória (Outras)"},
		Structs.DocumentCNJ{"746", "463", "Carta Precatória Citatória"},
		Structs.DocumentCNJ{"747", "463", "Carta Precatória Intimatória"},
		Structs.DocumentCNJ{"748", "470", "Certidão de Ausência de CPF/CNPJ"},
		Structs.DocumentCNJ{"749", "470", "Certidão de Ausência de Procuração"},
		Structs.DocumentCNJ{"750", "470", "Certidão de Ausência de Recolhimento de Custas"},
		Structs.DocumentCNJ{"751", "474", "Certidão de Baixa (Outras)"},
		Structs.DocumentCNJ{"752", "474", "Certidão de Baixa de Parte"},
		Structs.DocumentCNJ{"753", "479", "Certidão de Consulta de Renajud"},
		Structs.DocumentCNJ{"754", "479", "Certidão de Consulta de Serasajud"},
		Structs.DocumentCNJ{"755", "479", "Protocolo Sisbajud"},
		Structs.DocumentCNJ{"756", "480", "Certidão de Crédito Judicial"},
		Structs.DocumentCNJ{"757", "480", "Certidão de Crédito para Habilitação no Juízo Falimentar"},
		Structs.DocumentCNJ{"758", "480", "Certidão de Crédito Trabalhista"},
		Structs.DocumentCNJ{"759", "486", "Certidão de Devolução de AR por Ausência"},
		Structs.DocumentCNJ{"760", "486", "Certidão de Devolução de AR por Cumprimento"},
		Structs.DocumentCNJ{"761", "486", "Certidão de Devolução de AR por Desconhecimento"},
		Structs.DocumentCNJ{"762", "486", "Certidão de Devolução de AR por Insuficiência de Endereço"},
		Structs.DocumentCNJ{"763", "486", "Certidão de Devolução de AR por Mudança de Endereço"},
		Structs.DocumentCNJ{"764", "491", "Certidão de Expedição (Outras)"},
		Structs.DocumentCNJ{"765", "491", "Certidão de Expedição de AR"},
		Structs.DocumentCNJ{"766", "496", "Certidão de Inclusão em Cadastro de Inadimplente"},
		Structs.DocumentCNJ{"767", "496", "Certidão de Inclusão em Pauta"},
		Structs.DocumentCNJ{"768", "501", "Certidão de Intimação (Outros)"},
		Structs.DocumentCNJ{"769", "501", "Certidão de Intimação por Telefone"},
		Structs.DocumentCNJ{"770", "503", "Certidão de Julgamento (Outros)"},
		Structs.DocumentCNJ{"771", "503", "Certidão de Julgamento Colegiado"},
		Structs.DocumentCNJ{"775", "536", "Ementa"},
		Structs.DocumentCNJ{"776", "536", "Esclarecimentos"},
		Structs.DocumentCNJ{"777", "536", "Extrato da Ata"},
		Structs.DocumentCNJ{"778", "536", "Nota Oral"},
		Structs.DocumentCNJ{"779", "536", "Relatório"},
		Structs.DocumentCNJ{"780", "536", "Súmula"},
		Structs.DocumentCNJ{"781", "536", "Voto"},
		Structs.DocumentCNJ{"782", "537", "Autorização de Viagem"},
		Structs.DocumentCNJ{"783", "537", "Autorização de Visita"},
		Structs.DocumentCNJ{"784", "537", "Autorização Judicial - Art.122, I e III, LEP"},
		Structs.DocumentCNJ{"785", "537", "Autorização Judicial (Outros)"},
		Structs.DocumentCNJ{"786", "537", "Salvo-Conduto"},
		Structs.DocumentCNJ{"787", "538", "Decisão Monocrática Terminativa Com Resolução de Mérito"},
		Structs.DocumentCNJ{"788", "538", "Decisão Monocrática Terminativa Sem Resolução de Mérito"},
		Structs.DocumentCNJ{"789", "541", "Conversão"},
		Structs.DocumentCNJ{"790", "541", "Decisão Parcial de Mérito"},
		Structs.DocumentCNJ{"791", "541", "Deferimento de Assistência Judiciária Gratuita"},
		Structs.DocumentCNJ{"792", "541", "Indeferimento de Assistência Judiciária Gratuita"},
		Structs.DocumentCNJ{"793", "541", "Recebimento da Denúncia"},
		Structs.DocumentCNJ{"794", "541", "Tutela Antecipada"},
		Structs.DocumentCNJ{"795", "550", "Sentença (Outras)"},
		Structs.DocumentCNJ{"796", "550", "Sentença Normativa"},
		Structs.DocumentCNJ{"797", "567", "Edital de Leilão (Outros)"},
		Structs.DocumentCNJ{"798", "567", "Edital de Leilão 1ª Praça"},
		Structs.DocumentCNJ{"799", "567", "Edital de Leilão 2ª Praça"},
		Structs.DocumentCNJ{"800", "567", "Edital de Leilão Único"},
		Structs.DocumentCNJ{"801", "571", "Citação (Outros)"},
		Structs.DocumentCNJ{"802", "571", "Citação e Intimação para Audiência de Conciliação"},
		Structs.DocumentCNJ{"803", "572", "Conversão do Arresto em Penhora"},
		Structs.DocumentCNJ{"804", "572", "Conversão em Diligência"},
		Structs.DocumentCNJ{"805", "575", "Intimação (Outros)"},
		Structs.DocumentCNJ{"806", "575", "Intimação para Audiência de Instrução"},
		Structs.DocumentCNJ{"807", "595", "Mandado de Afastamento (Outros)"},
		Structs.DocumentCNJ{"808", "595", "Mandado de Afastamento e Intimação para Audiência e Outras Medidas (Lei n.11340/2006)"},
		Structs.DocumentCNJ{"809", "600", "Mandado de Arresto (Outros)"},
		Structs.DocumentCNJ{"810", "600", "Mandado de Arresto e Avaliação"},
		Structs.DocumentCNJ{"811", "603", "Mandado de Avaliação (Outros)"},
		Structs.DocumentCNJ{"812", "603", "Mandado de Avaliação e Remoção"},
		Structs.DocumentCNJ{"813", "603", "Mandado de Avaliação Indireta"},
		Structs.DocumentCNJ{"814", "607", "Mandado de Busca e Apreensão (Outros)"},
		Structs.DocumentCNJ{"815", "607", "Mandado de Busca e Apreensão de Autos"},
		Structs.DocumentCNJ{"816", "607", "Mandado de Busca e Apreensão de Criança e Adolescente"},
		Structs.DocumentCNJ{"817", "607", "Mandado de Busca e Apreensão de Pessoa por Oficial de Justiça"},
		Structs.DocumentCNJ{"818", "607", "Mandado de Busca, Apreensão e Depósito"},
		Structs.DocumentCNJ{"819", "608", "Mandado de Citação (Outros)"},
		Structs.DocumentCNJ{"820", "608", "Mandado de Citação e Separação de Corpos"},
		Structs.DocumentCNJ{"821", "608", "Mandado de Citação por Via Postal"},
		Structs.DocumentCNJ{"822", "608", "Mandado de Citação, Intimação e Imissão na Posse"},
		Structs.DocumentCNJ{"823", "608", "Mandado de Citação, Intimação e Manutenção de Posse"},
		Structs.DocumentCNJ{"824", "608", "Mandado de Citação, Intimação, Penhora e Avaliação"},
		Structs.DocumentCNJ{"825", "608", "Mandado de Citação, Penhora e Avaliação"},
		Structs.DocumentCNJ{"826", "613", "Mandado de Convocação (Outros)"},
		Structs.DocumentCNJ{"827", "613", "Mandado de Convocação de Jurado"},
		Structs.DocumentCNJ{"828", "619", "Mandado de Despejo (Outros)"},
		Structs.DocumentCNJ{"829", "619", "Mandado de Despejo com Audiência Preliminar"},
		Structs.DocumentCNJ{"830", "621", "Mandado de Entrega (Outros)"},
		Structs.DocumentCNJ{"831", "621", "Mandado de Entrega de Bens Arrematados/Adjudicados"},
		Structs.DocumentCNJ{"832", "622", "Mandado de Imissão na Posse (Outros)"},
		Structs.DocumentCNJ{"833", "622", "Mandado de Imissão na Posse em Bens Móveis"},
		Structs.DocumentCNJ{"834", "624", "Mandado de Intimação (Outros)"},
		Structs.DocumentCNJ{"835", "624", "Mandado de Intimação de Hasta Pública"},
		Structs.DocumentCNJ{"836", "624", "Mandado de Intimação de Medidas Protetivas"},
		Structs.DocumentCNJ{"837", "624", "Mandado de Intimação de Sentença"},
		Structs.DocumentCNJ{"838", "624", "Mandado de Intimação de Transação Penal"},
		Structs.DocumentCNJ{"839", "624", "Mandado de Intimação e Notificação"},
		Structs.DocumentCNJ{"840", "624", "Mandado de Intimação e Penhora"},
		Structs.DocumentCNJ{"841", "624", "Mandado de Intimação e Reforço de Penhora"},
		Structs.DocumentCNJ{"842", "624", "Mandado de Intimação e Remoção"},
		Structs.DocumentCNJ{"843", "624", "Mandado de Intimação para Audiência"},
		Structs.DocumentCNJ{"844", "624", "Mandado de Intimação para Devolução de Autos"},
		Structs.DocumentCNJ{"845", "624", "Mandado de Intimação para Perícia"},
		Structs.DocumentCNJ{"846", "624", "Mandado de Intimação, Penhora e Avaliação"},
		Structs.DocumentCNJ{"847", "625", "Mandado de Interceptação Telefônica"},
		Structs.DocumentCNJ{"848", "625", "Mandado de Interceptação Telemática"},
		Structs.DocumentCNJ{"849", "629", "Mandado de Notificação (Outros)"},
		Structs.DocumentCNJ{"850", "629", "Mandado de Notificação em Improbidade Administrativa"},
		Structs.DocumentCNJ{"851", "629", "Mandado de Notificação para Bloqueio"},
		Structs.DocumentCNJ{"852", "630", "Mandado de Ordem de Desinternação"},
		Structs.DocumentCNJ{"853", "630", "Mandado de Ordem de Liberação"},
		Structs.DocumentCNJ{"854", "632", "Mandado de Penhora (Outros)"},
		Structs.DocumentCNJ{"855", "632", "Mandado de Penhora de Créditos Bancários"},
		Structs.DocumentCNJ{"856", "632", "Mandado de Penhora e Avaliação"},
		Structs.DocumentCNJ{"857", "632", "Mandado de Penhora no Rosto dos Autos"},
		Structs.DocumentCNJ{"858", "632", "Mandado de Reforço de Penhora e Avaliação"},
		Structs.DocumentCNJ{"859", "633", "Mandado de Prisão Civil por Falta de Prestação Alimentícia"},
		Structs.DocumentCNJ{"860", "633", "Mandado de Prisão Domiciliar"},
		Structs.DocumentCNJ{"861", "633", "Mandado de Prisão em Razão de Conversão de Pena Restritiva"},
		Structs.DocumentCNJ{"862", "633", "Mandado de Prisão em Razão de Execução Penal"},
		Structs.DocumentCNJ{"863", "633", "Mandado de Prisão Preventiva"},
		Structs.DocumentCNJ{"864", "633", "Mandado de Prisão Temporária"},
		Structs.DocumentCNJ{"865", "636", "Mandado de Registro (Outros)"},
		Structs.DocumentCNJ{"866", "636", "Mandado de Registro de Nascimento"},
		Structs.DocumentCNJ{"867", "636", "Mandado de Registro de Óbito"},
		Structs.DocumentCNJ{"868", "636", "Mandado de Registro de Penhora"},
		Structs.DocumentCNJ{"869", "638", "Mandado de Remoção (Outros)"},
		Structs.DocumentCNJ{"870", "638", "Mandado de Remoção, Ref.de Penhora e Avaliação"},
		Structs.DocumentCNJ{"871", "640", "Mandado de Retificação Registros Públicos"},
		Structs.DocumentCNJ{"872", "646", "Mandado de Vistoria de Imóvel"},
		Structs.DocumentCNJ{"873", "646", "Mandado de Vistoria e Liberação de Bem"},
		Structs.DocumentCNJ{"874", "678", "Termo de Aplicação de Advertência"},
		Structs.DocumentCNJ{"875", "678", "Termo de Aplicação de Censura"},
		Structs.DocumentCNJ{"876", "678", "Termo de Aplicação de Multa"},
		Structs.DocumentCNJ{"877", "678", "Termo de Aplicação de Suspensão"},
		Structs.DocumentCNJ{"878", "681", "Termo de Audiência (Outros)"},
		Structs.DocumentCNJ{"879", "681", "Termo de Audiência de Custódia"},
		Structs.DocumentCNJ{"880", "687", "Termo de Compensação de Débito Tributário (Outros)"},
		Structs.DocumentCNJ{"881", "687", "Termo de Compensação de Débito Tributário com Precatório"},
		Structs.DocumentCNJ{"882", "688", "Termo de Compromisso (Outros)"},
		Structs.DocumentCNJ{"883", "688", "Termo de Compromisso de Fiel Depositário"},
		Structs.DocumentCNJ{"884", "688", "Termo de Compromisso de Inventariante"},
		Structs.DocumentCNJ{"885", "698", "Termo de Penhora (Outros)"},
		Structs.DocumentCNJ{"886", "698", "Termo de Penhora nos Autos"},
		Structs.DocumentCNJ{"887", "753", "Certidão de Consulta de Renajud Positiva"},
		Structs.DocumentCNJ{"888", "753", "Certidão de Consulta de Renajud Negativa"},
		Structs.DocumentCNJ{"889", "754", "Certidão de Consulta de SerasajudPositiva"},
		Structs.DocumentCNJ{"890", "754", "Certidão de Consulta de Serasajud Negativa"},
		Structs.DocumentCNJ{"891", "755", "Protocolo Sisbajud Positivo"},
		Structs.DocumentCNJ{"892", "755", "Protocolo Sisbajud Negativo"},
		Structs.DocumentCNJ{"893", "781", "Voto Desempate"},
		Structs.DocumentCNJ{"894", "781", "Voto Mérito"},
		Structs.DocumentCNJ{"895", "781", "Voto Preliminar"},
		Structs.DocumentCNJ{"896", "781", "Voto Revisão"},
		Structs.DocumentCNJ{"897", "781", "Voto Vencedor"},
		Structs.DocumentCNJ{"898", "781", "Voto Vencido"},
		Structs.DocumentCNJ{"899", "781", "Voto Vista"},
		Structs.DocumentCNJ{"900", "781", "Voto Vogal"},
		Structs.DocumentCNJ{"901", "789", "Conversão de Ação Monitória em Execução"},
		Structs.DocumentCNJ{"902", "789", "Conversão de Prisão em Flagrante para Preventiva"},
		Structs.DocumentCNJ{"903", "789", "Conversão de Prisão em Flagrante para Temporária"},
		Structs.DocumentCNJ{"904", "794", "Concessão Liminar dos Efeitos da Tutela Antecipada"},
		Structs.DocumentCNJ{"905", "794", "Concessão Liminar em Parte dos Efeitos da Tutela Antecipada"},
		Structs.DocumentCNJ{"906", "794", "Denegação da Medida Liminar de Antecipação de Tutela"},
		Structs.DocumentCNJ{"907", "604", "Mandado de Averbação e Cancelamento de Novo Registro"},
		Structs.DocumentCNJ{"908", "604", "Mandado de Averbação de Sentença"},
		Structs.DocumentCNJ{"909", "604", "Mandado de Averbação (Outros)"},
		Structs.DocumentCNJ{"910", "908", "Mandado de Averbação de Sentença em Registro Civil"},
		Structs.DocumentCNJ{"911", "908", "Mandado de Averbação de Sentença em Registro de Imóveis"},
		Structs.DocumentCNJ{"912", "816", "Mandado de Busca e Apreensão de Criança e Adolescente por Autoridade Policial"},
		Structs.DocumentCNJ{"913", "816", "Mandado de Busca e Apreensão de Criança e Adolescente por Oficial de Justiça"},
		Structs.DocumentCNJ{"914", "843", "Mandado de Intimação para Audiência Admonitória"},
		Structs.DocumentCNJ{"915", "843", "Mandado de Intimação para Audiência de Partes e Advogados"},
		Structs.DocumentCNJ{"916", "843", "Mandado de Intimação de Audiência de Suposto Pai"},
		Structs.DocumentCNJ{"917", "843", "Mandado de Intimação de Audiência de Terceiros"},
		Structs.DocumentCNJ{"919", "843", "Mandado de Intimação de Audiência de Testemunhas"},
		Structs.DocumentCNJ{"920", "843", "Mandado de Intimação de Audiência (Outros)"},
		Structs.DocumentCNJ{"921", "843", "Mandado de Intimação para Audiência, Penhora e Avaliação"},
		Structs.DocumentCNJ{"922", "840", "Mandado de Intimação e Penhora no Rosto dos Autos e de Cumprimento de Sentença"},
		Structs.DocumentCNJ{"923", "840", "Mandado de Intimação e Penhora no Termo dos Autos e Cumprimento de Sentença"},
		Structs.DocumentCNJ{"924", "840", "Mandado de Intimação e Penhora (Outros)"},
		Structs.DocumentCNJ{"925", "841", "Mandado de Intimação, Reforço de Penhora e Avaliação"},
		Structs.DocumentCNJ{"926", "841", "Mandado de Intimação e Reforço de Penhora (Outros)"},
		Structs.DocumentCNJ{"927", "846", "Mandado de Intimação, Penhora, Avaliação e Remoção"},
		Structs.DocumentCNJ{"928", "846", "Mandado de intimação, Penhora e Avaliação (Outros)"},
		Structs.DocumentCNJ{"929", "847", "Mandado de Cancelamento de Interceptação Telefônica"},
		Structs.DocumentCNJ{"930", "847", "Mandado de Determinação de interceptação Telefônica"},
		Structs.DocumentCNJ{"931", "847", "Mandado de Prorrogação de Interceptação Telefônica"},
		Structs.DocumentCNJ{"932", "848", "Mandado de Cancelamento de Interceptação Telemática"},
		Structs.DocumentCNJ{"933", "848", "Mandado de Determinação de interceptação Telemática"},
		Structs.DocumentCNJ{"934", "848", "Mandado de Prorrogação de Interceptação Telemática"},
		Structs.DocumentCNJ{"935", "862", "Mandado de Prisão em Razão de Execução Penal Definitiva"},
		Structs.DocumentCNJ{"936", "862", "Mandado de Prisão em Razão de Execução Provisória"},
		Structs.DocumentCNJ{"937", "871", "Mandado de Retificação de Registro de Casamento"},
		Structs.DocumentCNJ{"938", "871", "Mandado de Retificação de Registro de Nascimento"},
		Structs.DocumentCNJ{"939", "871", "Mandado de Retificação de Registro de Óbito"},
		Structs.DocumentCNJ{"940", "871", "Mandado de Retificação de Registro Público (Outros)"},
		Structs.DocumentCNJ{"941", "536", "Comunicação"},
		Structs.DocumentCNJ{"14242", "542", "Juízo de Admissibilidade de Recurso Adesivo"},
		Structs.DocumentCNJ{"14243", "542", "Agravo"},
		Structs.DocumentCNJ{"14244", "14243", "Juízo de Admissibilidade de Agravo de Instrumento"},
		Structs.DocumentCNJ{"14245", "14243", "Juízo de Admissibilidade em Agravo em Pedido de Interpretação de Lei Federal"},
		Structs.DocumentCNJ{"14246", "14243", "Juízo de Admissibilidade de Agravo em Recurso Especial"},
		Structs.DocumentCNJ{"14247", "14243", "Juízo de Admissibilidade de Agravo em Recurso Extraordinário"},
		Structs.DocumentCNJ{"14248", "14243", "Juízo de Admissibilidade de Agravo em Recurso Ordinário"},
		Structs.DocumentCNJ{"14249", "14243", "Juízo de Admissibilidade de Agravo Inominado ou Legal"},
		Structs.DocumentCNJ{"14250", "14243", "Juízo de Admissibilidade de Agravo Interno"},
		Structs.DocumentCNJ{"14251", "14243", "Juízo de Admissibilidade de Agravo Regimental"},
		Structs.DocumentCNJ{"14252", "14243", "Juízo de Admissibilidade de Agravo Retido"},
		Structs.DocumentCNJ{"14253", "542", "Juízo de Admissibilidade de Apelação"},
		Structs.DocumentCNJ{"14254", "542", "Juízo de Admissibilidade de Correição Parcial"},
		Structs.DocumentCNJ{"14255", "542", "Embargos"},
		Structs.DocumentCNJ{"14256", "14255", "Juízo de Admissibilidade de Embargos de Declaração"},
		Structs.DocumentCNJ{"14257", "14255", "Juízo de Admissibilidade de Embargos de Divergência"},
		Structs.DocumentCNJ{"14258", "14255", "Juízo de Admissibilidade de Embargos em Ação Penal"},
		Structs.DocumentCNJ{"14259", "14255", "Juízo de Admissibilidade de Embargos Infringentes"},
		Structs.DocumentCNJ{"14260", "14255", "Juízo de Admissibilidade de Embargos Infringentes e de Nulidade"},
		Structs.DocumentCNJ{"14261", "542", "Juízo de Admissibilidade de Recurso Administrativo"},
		Structs.DocumentCNJ{"14262", "542", "Juízo de Admissibilidade de Recurso Criminal Eleitoral"},
		Structs.DocumentCNJ{"14263", "542", "Juízo de Admissibilidade de Recurso de Revista"},
		Structs.DocumentCNJ{"14264", "542", "Juízo de Admissibilidade de Recurso Eleitoral"},
		Structs.DocumentCNJ{"14265", "542", "Juízo de Admissibilidade de Recurso em Direito de Resposta"},
		Structs.DocumentCNJ{"14266", "542", "Juízo de Admissibilidade de Recurso em Reclamação"},
		Structs.DocumentCNJ{"14267", "542", "Juízo de Admissibilidade de Recurso em Representação"},
		Structs.DocumentCNJ{"14268", "542", "Juízo de Admissibilidade de Recurso em Sentido Estrito"},
		Structs.DocumentCNJ{"14269", "542", "Juízo de Admissibilidade de Recurso Especial"},
		Structs.DocumentCNJ{"14270", "542", "Juízo de Admissibilidade de Recurso Especial Eleitoral"},
		Structs.DocumentCNJ{"14271", "542", "Juízo de Admissibilidade de Recurso Extraordinário"},
		Structs.DocumentCNJ{"14272", "542", "Juízo de Admissibilidade de Recurso Inominado"},
		Structs.DocumentCNJ{"14273", "542", "Juízo de Admissibilidade de Recurso Ordinário"},
		Structs.DocumentCNJ{"14274", "11", "Acordo de Divórcio"},
		Structs.DocumentCNJ{"14275", "11", "Acordo Resp. Parentais"},
		Structs.DocumentCNJ{"14276", "3", "Apostila"},
		Structs.DocumentCNJ{"14277", "17", "Contraminuta de Agravo em Recurso Especial"},
		Structs.DocumentCNJ{"14278", "17", "Contraminuta de Agravo em Recurso Extraordinário"},
		Structs.DocumentCNJ{"14279", "17", "Contraminuta do Agravo em Recurso Ordinário"},
		Structs.DocumentCNJ{"14280", "18", "Contrarrazões ao Recurso Especial"},
		Structs.DocumentCNJ{"14281", "18", "Contrarrazões ao Recurso Extraordinário"},
		Structs.DocumentCNJ{"14282", "18", "Contrarrazões ao Incidente de Uniformização Nacional"},
		Structs.DocumentCNJ{"14283", "18", "Contrarrazões ao Incidente de Uniformização Regional"},
		Structs.DocumentCNJ{"14284", "18", "Contrarrazões ao IUSTJ"},
		Structs.DocumentCNJ{"14285", "18", "Contrarrazões ao Recurso Inominado"},
		Structs.DocumentCNJ{"14286", "18", "Contrarrazões da Apelação"},
		Structs.DocumentCNJ{"14287", "4", "Decisão Estrangeira"},
		Structs.DocumentCNJ{"14288", "4", "Declaração de Anuência"},
		Structs.DocumentCNJ{"14289", "4", "Legislação"},
		Structs.DocumentCNJ{"14290", "4", "Sentença Estrangeira"},
		Structs.DocumentCNJ{"14291", "4", "Tradução"},
		Structs.DocumentCNJ{"14292", "536", "Acórdão da Apelação"},
		Structs.DocumentCNJ{"14293", "536", "Acórdão da Turma Nacional"},
		Structs.DocumentCNJ{"14294", "536", "Acórdão da Turma Recursa"},
		Structs.DocumentCNJ{"14295", "536", "Acórdão da Turma Regional"},
		Structs.DocumentCNJ{"14296", "536", "Acórdão de Admissibilidade do IRDR"},
		Structs.DocumentCNJ{"14297", "536", "Acórdão do Agravo de Instrumento"},
		Structs.DocumentCNJ{"14298", "536", "Acórdão do Agravo Regimental"},
		Structs.DocumentCNJ{"14299", "536", "Acórdão dos Embargos de Declaração"},
		Structs.DocumentCNJ{"14300", "536", "Acórdão dos Embargos de Declaração nos Embargos Infringentes"},
		Structs.DocumentCNJ{"14301", "536", "Acórdão dos Embargos Infringentes"},
		Structs.DocumentCNJ{"14302", "542", "Admissibilidade do Incidente de Uniformização"},
		Structs.DocumentCNJ{"14303", "542", "Admissibilidade do Pedido de Uniformização"},
		Structs.DocumentCNJ{"14304", "423", "Termo de Arquivamento"},
		Structs.DocumentCNJ{"14305", "423", "Termo de Ciência"},
		Structs.DocumentCNJ{"14306", "4", "Dados Bancários"},
		Structs.DocumentCNJ{"14307", "11", "Acordo Extrajudicial"},
		Structs.DocumentCNJ{"14308", "3", "Arresto"},
		Structs.DocumentCNJ{"14309", "3", "Apresentação de Quesitos/Indicação de Assistente Técnico"},
		Structs.DocumentCNJ{"14310", "3", "Cessão de Crédito"},
		Structs.DocumentCNJ{"14311", "3", "Representação - Ato Infracional"},
		Structs.DocumentCNJ{"14312", "3", "Documentos Intermediários - DELPOL"},
		Structs.DocumentCNJ{"14313", "24", "Exceção da Verdade"},
		Structs.DocumentCNJ{"14314", "25", "Execução da Multa Penal"},
		Structs.DocumentCNJ{"14315", "3", "Exibição"},
		Structs.DocumentCNJ{"14316", "26", "Impugnação ao Cumprimento de Decisão"},
		Structs.DocumentCNJ{"14317", "28", "Incidente de Excesso ou Desvio"},
		Structs.DocumentCNJ{"14318", "29", "Informações  - Agravo de Instrumento "},
		Structs.DocumentCNJ{"14319", "29", "Informações - Habeas Corpus"},
		Structs.DocumentCNJ{"14320", "29", "Informações - Habeas Data"},
		Structs.DocumentCNJ{"14321", "31", "Manifestação da Defensoria Pública"},
		Structs.DocumentCNJ{"14322", "31", "Manifestação do Perito"},
		Structs.DocumentCNJ{"14323", "36", "Pedido (Outros)"},
		Structs.DocumentCNJ{"14324", "36", "Pedido de Aceite de Bens Oferecidos em Garantia"},
		Structs.DocumentCNJ{"14325", "36", "Pedido de Adjudicação"},
		Structs.DocumentCNJ{"14326", "36", "Pedido de Alvará de Soltura"},
		Structs.DocumentCNJ{"14327", "36", "Pedido de Anistia"},
		Structs.DocumentCNJ{"14328", "36", "Pedido de Citação por Edital"},
		Structs.DocumentCNJ{"14329", "36", "Pedido de Comutação da Pena"},
		Structs.DocumentCNJ{"14330", "36", "Pedido de Contramandado de Prisão"},
		Structs.DocumentCNJ{"14331", "36", "Pedido de Concessão de Livramento Condicional"},
		Structs.DocumentCNJ{"14332", "36", "Pedido de Conversão de Pena"},
		Structs.DocumentCNJ{"14333", "36", "Pedido de Conversão de Pena - Superveniência de Doença Mental"},
		Structs.DocumentCNJ{"14334", "36", "Pedido de Desbloqueio Penhora Online/Sisbajud"},
		Structs.DocumentCNJ{"14335", "36", "Pedido de Desconsideração da Personalidade Jurídica"},
		Structs.DocumentCNJ{"14336", "14335", "Pedido de Desconsideração Inversa da Personalidade Jurídica"},
		Structs.DocumentCNJ{"14337", "36", "Pedido de Desentranhamento de Documentos"},
		Structs.DocumentCNJ{"14338", "36", "Pedido de Designação/Redesignação de Audiência"},
		Structs.DocumentCNJ{"14339", "36", "Pedido de Renúncia da Nomeação - Auxiliares da Justiça"},
		Structs.DocumentCNJ{"14340", "36", "Pedido de Dilação de Prazo"},
		Structs.DocumentCNJ{"14341", "36", "Pedido de Documentos - Auxiliares da Justiça"},
		Structs.DocumentCNJ{"14342", "36", "Pedido de Expedição"},
		Structs.DocumentCNJ{"14343", "14342", "Pedido de Expedição de Alvará"},
		Structs.DocumentCNJ{"14344", "14342", "Pedido de Expedição de Carta Precatória"},
		Structs.DocumentCNJ{"14345", "14342", "Pedido de Expedição de Guia de Levantamento"},
		Structs.DocumentCNJ{"14346", "14342", "Pedido de Expedição de Ofício"},
		Structs.DocumentCNJ{"14347", "36", "Pedido de Inclusão"},
		Structs.DocumentCNJ{"14348", "14347", "Pedido de Inclusão de Espólio no Polo Passivo"},
		Structs.DocumentCNJ{"14349", "14347", "Pedido de Inclusão de Responsável Tributário"},
		Structs.DocumentCNJ{"14350", "14347", "Pedido de Inclusão, Exclusão ou Substituição do Polo Passivo"},
		Structs.DocumentCNJ{"14351", "36", "Pedido de Indulto"},
		Structs.DocumentCNJ{"14352", "36", "Pedido de Intimação de Administrador Judicial"},
		Structs.DocumentCNJ{"14353", "36", "Pedido de Juntada de Comprovante de Recolhimento das Custas Finais "},
		Structs.DocumentCNJ{"14354", "36", "Pedido de Levantamento de Curatela"},
		Structs.DocumentCNJ{"14355", "36", "Pedido de Penhora"},
		Structs.DocumentCNJ{"14356", "14355", "Nomeação de Bens à Penhora "},
		Structs.DocumentCNJ{"14357", "36", "Pedido de Prisão Domiciliar"},
		Structs.DocumentCNJ{"14358", "36", "Pedido de Progressão de Regime Aberto"},
		Structs.DocumentCNJ{"14359", "36", "Pedido de Progressão de Regime Semiaberto "},
		Structs.DocumentCNJ{"14360", "36", "Pedido de Regressão de Regime"},
		Structs.DocumentCNJ{"14361", "36", "Pedido de Regressão de Regime - Cautelar"},
		Structs.DocumentCNJ{"14362", "36", "Pedido  de Remição"},
		Structs.DocumentCNJ{"14363", "36", "Pedido de Retificação de Cálculo da Pena"},
		Structs.DocumentCNJ{"14364", "36", "Pedido de Sobrestamento de Recurso Repetitivo"},
		Structs.DocumentCNJ{"14365", "36", "Pedido de Vista dos Autos"},
		Structs.DocumentCNJ{"14366", "37", "Endereço Sigiloso - Violência Doméstica"},
		Structs.DocumentCNJ{"14367", "3", "Relatório Final Delpol"},
		Structs.DocumentCNJ{"14368", "227", "Embargos (outros)"},
		Structs.DocumentCNJ{"14369", "47", "Resposta aos Embargos à Adjudicação/Alienação/Arrematação"},
		Structs.DocumentCNJ{"14370", "4", "Ata"},
		Structs.DocumentCNJ{"14371", "57", "Atestado de Conduta Carcerária"},
		Structs.DocumentCNJ{"14372", "57", "Atestado de Pena"},
		Structs.DocumentCNJ{"14373", "57", "Atestado de Remição"},
		Structs.DocumentCNJ{"14374", "56", "Auto de Acareação"},
		Structs.DocumentCNJ{"14375", "56", "Auto de Apreensão"},
		Structs.DocumentCNJ{"14376", "56", "Auto de Apresentação"},
		Structs.DocumentCNJ{"14377", "56", "Auto de Arrematação"},
		Structs.DocumentCNJ{"14378", "56", "Auto de Avaliação"},
		Structs.DocumentCNJ{"14379", "56", "Auto de Constatação"},
		Structs.DocumentCNJ{"14380", "14379", "Auto de Constatação de Substância Entorpecente"},
		Structs.DocumentCNJ{"14381", "14379", "Auto de Constatação e Imissão na Posse"},
		Structs.DocumentCNJ{"14382", "56", "Auto de Infração"},
		Structs.DocumentCNJ{"14383", "56", "Auto de Penhora"},
		Structs.DocumentCNJ{"14384", "56", "Auto de Qualificação"},
		Structs.DocumentCNJ{"14385", "56", "Auto de Recognição"},
		Structs.DocumentCNJ{"14386", "4", "Boletim de Ocorrência"},
		Structs.DocumentCNJ{"14387", "60", "Aviso de Recebimento (AR) - Negativo"},
		Structs.DocumentCNJ{"14388", "60", "Aviso de Recebimento (AR) - Positivo"},
		Structs.DocumentCNJ{"14389", "62", "Cálculo do Imposto ITCMD"},
		Structs.DocumentCNJ{"14390", "62", "Cálculo Judicial"},
		Structs.DocumentCNJ{"14391", "66", "Certidão Carcerária"},
		Structs.DocumentCNJ{"14392", "66", "Certidão da Junta Comercial"},
		Structs.DocumentCNJ{"14393", "66", "Certidão de Antecedentes Penais "},
		Structs.DocumentCNJ{"14394", "66", "Certidão de Casamento"},
		Structs.DocumentCNJ{"14395", "66", "Certidão de Informações de Tributo Imobiliário - Imóvel"},
		Structs.DocumentCNJ{"14396", "66", "Certidão de Nascimento"},
		Structs.DocumentCNJ{"14397", "70", "Comprovante de Multa Paga"},
		Structs.DocumentCNJ{"14398", "70", "Comprovante de Pagamento"},
		Structs.DocumentCNJ{"14399", "73", "Contrato de Honorários Advocatícios"},
		Structs.DocumentCNJ{"14400", "4", "Declaração de União Estável"},
		Structs.DocumentCNJ{"14401", "83", "Agendamento de Vistoria - Prova Pericial - Art. 474 do CPC"},
		Structs.DocumentCNJ{"14402", "83", "Prestação de Contas do Perito"},
		Structs.DocumentCNJ{"14403", "4", "Documentos Diversos"},
		Structs.DocumentCNJ{"14404", "4", "Edital"},
		Structs.DocumentCNJ{"14405", "4", "Exame de Confronto Grafotécnico"},
		Structs.DocumentCNJ{"14406", "4", "Exame de Corpo de Delito"},
		Structs.DocumentCNJ{"14407", "90", "Extrato (Outros)"},
		Structs.DocumentCNJ{"14408", "91", "Ficha de Atendimento Médico"},
		Structs.DocumentCNJ{"14409", "91", "Ficha do Réu/Prontuário"},
		Structs.DocumentCNJ{"14410", "91", "Histórico Funcional"},
		Structs.DocumentCNJ{"14411", "4", "Formal de Partilha"},
		Structs.DocumentCNJ{"14412", "4", "Formulários"},
		Structs.DocumentCNJ{"14413", "94", "Guia de Acolhimento/Desacolhimento"},
		Structs.DocumentCNJ{"14414", "94", "Guia de Execução"},
		Structs.DocumentCNJ{"14415", "303", "Guia de Recolhimento Definitiva"},
		Structs.DocumentCNJ{"14416", "303", "Guia de Recolhimento Provisória"},
		Structs.DocumentCNJ{"14417", "4", "Informações sobre Antecedentes do Adolescente (Infracional)"},
		Structs.DocumentCNJ{"14418", "313", "Laudo de Perícia - Sigiloso"},
		Structs.DocumentCNJ{"14419", "313", "Laudo de Perícia - Não Sigiloso"},
		Structs.DocumentCNJ{"14420", "100", "Laudo Médico"},
		Structs.DocumentCNJ{"14421", "100", "Laudo Psicológico"},
		Structs.DocumentCNJ{"14422", "100", "Laudo IC"},
		Structs.DocumentCNJ{"14423", "100", "Laudo IML"},
		Structs.DocumentCNJ{"14424", "100", "Laudo Pirenecroscópico"},
		Structs.DocumentCNJ{"14425", "4", "Levantamento"},
		Structs.DocumentCNJ{"14426", "4", "Nota de Culpa"},
		Structs.DocumentCNJ{"14427", "104", "Ofício Requisitório de RPV - Requisição de Pequeno Valor"},
		Structs.DocumentCNJ{"14428", "4", "Perfil Profissiográfico Previdenciário"},
		Structs.DocumentCNJ{"14429", "4", "Primeiras Declarações"},
		Structs.DocumentCNJ{"14430", "115", "Recibo de Pagamento"},
		Structs.DocumentCNJ{"14431", "118", "Relatório de Consulta à Comunidade Indígena"},
		Structs.DocumentCNJ{"14432", "118", "Relatório de Comparecimento (Execução Penal)"},
		Structs.DocumentCNJ{"14433", "118", "Relatório do Corpo Técnico"},
		Structs.DocumentCNJ{"14434", "118", "Relatório Mensal de Prestação de Serviços à Comunidade"},
		Structs.DocumentCNJ{"14435", "118", "Relatório de Investigações"},
		Structs.DocumentCNJ{"14436", "118", "Relatório Final"},
		Structs.DocumentCNJ{"14437", "4", "Rol de Testemunhas"},
		Structs.DocumentCNJ{"14438", "61", "Bloqueio/Penhora On Line Positivo"},
		Structs.DocumentCNJ{"14439", "61", "Bloqueio/Penhora On Line Negativo"},
		Structs.DocumentCNJ{"14440", "61", "Transferência - Bloqueio/Penhora On Line"},
		Structs.DocumentCNJ{"14441", "4", "Termo de Acordo"},
		Structs.DocumentCNJ{"14442", "6", "Acórdão"},
		Structs.DocumentCNJ{"14443", "398", "Alvará - Traslado dos Restos Mortais"},
		Structs.DocumentCNJ{"14444", "433", "Alvará de Soltura - Prisão Preventiva"},
		Structs.DocumentCNJ{"14445", "433", "Alvará de Soltura - Flagrante - Audiência de Custódia - Relaxamento de Prisão"},
		Structs.DocumentCNJ{"14446", "433", "Alvará de Soltura - Audiência de Custódia - Com Fiança"},
		Structs.DocumentCNJ{"14447", "433", "Alvará de Soltura - Relaxamento de Prisão"},
		Structs.DocumentCNJ{"14448", "433", "Alvará de Soltura - Sem Fiança"},
		Structs.DocumentCNJ{"14449", "433", "Alvará de Soltura - Com Fiança"},
		Structs.DocumentCNJ{"14450", "433", "Alvará de Soltura - Audiência de Custódia - Com Termo"},
		Structs.DocumentCNJ{"14451", "400", "Auto de Entrega de Objeto Apreendido "},
		Structs.DocumentCNJ{"14452", "400", "Auto de Hasta Negativa"},
		Structs.DocumentCNJ{"14453", "400", "Auto de Hasta Única"},
		Structs.DocumentCNJ{"14454", "401", "Carta - Cientificação"},
		Structs.DocumentCNJ{"14455", "402", "Certidão de Desarquivamento"},
		Structs.DocumentCNJ{"14456", "402", "Certidão - Ausência de Réplica"},
		Structs.DocumentCNJ{"14457", "402", "certidão - Ausência de Pagamento"},
		Structs.DocumentCNJ{"14458", "402", "Certidão - Ausência de Manifestação do Exequente"},
		Structs.DocumentCNJ{"14459", "402", "Certidão - Ausência de Manifestação sobre a Penhora On Line"},
		Structs.DocumentCNJ{"14460", "402", "Certidão - Ausência de Manifestação sobre Depósito - Busca e Apreensão"},
		Structs.DocumentCNJ{"14461", "402", "Certidão - Ausência de Contraminuta"},
		Structs.DocumentCNJ{"14462", "402", "Certidão - Ausência de Contrarrazões"},
		Structs.DocumentCNJ{"14463", "402", "Certidão de Consulta de Infojud"},
		Structs.DocumentCNJ{"14464", "14463", "Certidão de Consulta de Infojud - Positiva"},
		Structs.DocumentCNJ{"14465", "14463", "Certidão de Consulta de Infojud - Negativa"},
		Structs.DocumentCNJ{"14466", "404", "Decisão de Tribunal Superior"},
		Structs.DocumentCNJ{"14467", "415", "Mandado de Levantamento"},
		Structs.DocumentCNJ{"14468", "420", "Portaria - Instauração de Incidente de Insanidade Mental"},
		Structs.DocumentCNJ{"14469", "681", "Termo de Audiência - Com Acordo"},
		Structs.DocumentCNJ{"14470", "681", "Termo de Audiência - Sem Acordo"},
		Structs.DocumentCNJ{"14471", "4", "Anexo"},
		Structs.DocumentCNJ{"14472", "4", "Anotação de Responsabilidade Técnica - ART"},
		Structs.DocumentCNJ{"14473", "4", "Apostila"},
		Structs.DocumentCNJ{"14474", "4", "Certificado"},
		Structs.DocumentCNJ{"14475", "4", "Contrafé"},
		Structs.DocumentCNJ{"14476", "4", "Convênio"},
		Structs.DocumentCNJ{"14477", "4", "DANFE"},
		Structs.DocumentCNJ{"14478", "4", "DARF"},
		Structs.DocumentCNJ{"14479", "4", "Desenho"},
		Structs.DocumentCNJ{"14480", "4", "Diploma"},
		Structs.DocumentCNJ{"14481", "4", "Documento Pessoal"},
		Structs.DocumentCNJ{"14482", "4", "Estatuto"},
		Structs.DocumentCNJ{"14483", "4", "Execução de Despesa"},
		Structs.DocumentCNJ{"14484", "4", "Fatura"},
		Structs.DocumentCNJ{"14485", "4", "Fluxograma/Organograma"},
		Structs.DocumentCNJ{"14486", "4", "Folha de Pagamento"},
		Structs.DocumentCNJ{"14487", "4", "GRU"},
		Structs.DocumentCNJ{"14488", "4", "Informações (Outros)"},
		Structs.DocumentCNJ{"14489", "4", "Inventário"},
		Structs.DocumentCNJ{"14490", "4", "Licença"},
		Structs.DocumentCNJ{"14491", "4", "Lista"},
		Structs.DocumentCNJ{"14492", "4", "Manual"},
		Structs.DocumentCNJ{"14493", "4", "Memorando"},
		Structs.DocumentCNJ{"14494", "4", "Mídia"},
		Structs.DocumentCNJ{"14495", "4", "Monografia"},
		Structs.DocumentCNJ{"14496", "4", "Nota Fiscal"},
		Structs.DocumentCNJ{"14497", "4", "Pesquisa"},
		Structs.DocumentCNJ{"14498", "4", "Ordem Bancária"},
		Structs.DocumentCNJ{"14499", "4", "Ordem (Outros)"},
		Structs.DocumentCNJ{"14500", "4", "Nota (Outros)"},
		Structs.DocumentCNJ{"14501", "4", "Planilha (outros)"},
		Structs.DocumentCNJ{"14502", "4", "Plano"},
		Structs.DocumentCNJ{"14503", "4", "Pregão"},
		Structs.DocumentCNJ{"14504", "4", "Prestação de Contas"},
		Structs.DocumentCNJ{"14505", "4", "Processo Administrativo"},
		Structs.DocumentCNJ{"14506", "4", "Projeto"},
		Structs.DocumentCNJ{"14507", "4", "Prontuário"},
		Structs.DocumentCNJ{"14508", "4", "Protocolo (outros)"},
		Structs.DocumentCNJ{"14509", "4", "Reclamação"},
		Structs.DocumentCNJ{"14510", "4", "Recomendação"},
		Structs.DocumentCNJ{"14511", "4", "Regimento Interno"},
		Structs.DocumentCNJ{"14512", "4", "Regulamento"},
		Structs.DocumentCNJ{"14513", "4", "Requerimento (Outros)"},
		Structs.DocumentCNJ{"14514", "4", "Resolução"},
		Structs.DocumentCNJ{"14515", "185", "Pedido de Desistência da Execução"},
		Structs.DocumentCNJ{"14516", "50", "Renúncia ao direito sobre o qual se funda a ação"},
		Structs.DocumentCNJ{"14517", "3", "Certidão Dirigentes Partidários - SGIP"},
		Structs.DocumentCNJ{"14518", "3", "Diligência"},
		Structs.DocumentCNJ{"14519", "3", "Documento de Comprovação"},
		Structs.DocumentCNJ{"14520", "3", "Expediente"},
		Structs.DocumentCNJ{"14521", "3", "Outras Comprovações"},
		Structs.DocumentCNJ{"14522", "25", "Termo de Abertura de Liquidação"},
		Structs.DocumentCNJ{"14523", "25", "Termo de Abertura de Execução"},
		Structs.DocumentCNJ{"14575", "2", "Ato Ordinatório"},
		Structs.DocumentCNJ{"14576", "2", "Memorando"},
		Structs.DocumentCNJ{"14577", "2", "Movimento Processual"},
		Structs.DocumentCNJ{"14578", "2", "Protocolo de Distribuição"},
		Structs.DocumentCNJ{"14579", "2", "Resolução"},
		Structs.DocumentCNJ{"14580", "402", "Certidão de Expedição de Documento"},
		Structs.DocumentCNJ{"14581", "402", "Certidão de Inadimplência"},
		Structs.DocumentCNJ{"14582", "402", "Certidão 2ª Remessa"},
		Structs.DocumentCNJ{"14583", "781", "Voto Escrito"},
		Structs.DocumentCNJ{"14584", "781", "Voto Relator"},
		Structs.DocumentCNJ{"14585", "781", "Voto Retificador"},
		Structs.DocumentCNJ{"14586", "404", "Decisão Agravada"},
		Structs.DocumentCNJ{"14587", "409", "Despacho de Ofício"},
		Structs.DocumentCNJ{"14588", "409", "Despacho Revisor"},
		Structs.DocumentCNJ{"14589", "411", "Guia de Recolhimento da União - GRU"},
		Structs.DocumentCNJ{"14590", "412", "Espelho da Base"},
		Structs.DocumentCNJ{"14591", "412", "Espelho de Eleitor"},
		Structs.DocumentCNJ{"14592", "412", "Informação - Corregedoria"},
		Structs.DocumentCNJ{"14593", "412", "Informação Processual"},
		Structs.DocumentCNJ{"14594", "415", "Devolução de Mandado"},
		Structs.DocumentCNJ{"14595", "415", "Recebimento de Mandado"},
		Structs.DocumentCNJ{"14596", "417", "Devolução de Ofício"},
		Structs.DocumentCNJ{"14597", "417", "Recebimento de Ofício"},
		Structs.DocumentCNJ{"14598", "419", "Certidão de Publicação de Pauta"},
		Structs.DocumentCNJ{"14599", "419", "Intimação de Pauta"},
		Structs.DocumentCNJ{"14600", "422", "Relatório SISGRU"},
		Structs.DocumentCNJ{"14601", "3", "Prestação de Contas"},
		Structs.DocumentCNJ{"14602", "14601", "Agentes Responsáveis"},
		Structs.DocumentCNJ{"14603", "14601", "Aplicação de Recursos"},
		Structs.DocumentCNJ{"14604", "14601", "Aplicação Financeira"},
		Structs.DocumentCNJ{"14605", "14601", "Apresentação das Contas Finais Intempestiva"},
		Structs.DocumentCNJ{"14606", "14601", "Assunção Dívida"},
		Structs.DocumentCNJ{"14607", "14601", "Ativo Permanente"},
		Structs.DocumentCNJ{"14608", "14601", "Avulso Outro "},
		Structs.DocumentCNJ{"14609", "14601", "Avulso SPCA"},
		Structs.DocumentCNJ{"14610", "14601", "Avulso SPCE"},
		Structs.DocumentCNJ{"14611", "14601", "Bens e Direitos Estimáveis de Exercícios Anteriores"},
		Structs.DocumentCNJ{"14612", "14601", "Comercialização"},
		Structs.DocumentCNJ{"14613", "14601", "Conciliação Bancária"},
		Structs.DocumentCNJ{"14614", "14601", "Configurador de Ativos Não Circulantes"},
		Structs.DocumentCNJ{"14615", "14601", "Configurador de Direitos Realizáveis"},
		Structs.DocumentCNJ{"14616", "14601", "Configurador de Outros Itens Não Monetários de Exercícios Anteriores"},
		Structs.DocumentCNJ{"14617", "14601", "Conta Bancária"},
		Structs.DocumentCNJ{"14618", "14601", "Declaração Apresentação das Contas Finais"},
		Structs.DocumentCNJ{"14619", "14601", "Declaração Apresentação das Contas Retificadoras"},
		Structs.DocumentCNJ{"14620", "14601", "Declaração de Ausência de Movimentação"},
		Structs.DocumentCNJ{"14621", "14601", "Declaração de Juntada dos Demonstrativos"},
		Structs.DocumentCNJ{"14622", "14601", "Declaração de Juntada dos Documentos Comprobatórios"},
		Structs.DocumentCNJ{"14623", "14601", "Declaração de Reabertura da PC"},
		Structs.DocumentCNJ{"14624", "14601", "Despesa"},
		Structs.DocumentCNJ{"14625", "14601", "Devolução Receita"},
		Structs.DocumentCNJ{"14626", "14601", "Direitos Realizáveis"},
		Structs.DocumentCNJ{"14627", "14601", "Doação Estimável a Partidos e Candidatos"},
		Structs.DocumentCNJ{"14628", "14601", "Doação de Exercícios Anteriores a Partidos e Candidatos"},
		Structs.DocumentCNJ{"14629", "14601", "Doação Estimável de Itens Não Monetários de Exercícios Anteriores"},
		Structs.DocumentCNJ{"14630", "14601", "Doação Estimável de Itens Oriundos de Despesa"},
		Structs.DocumentCNJ{"14631", "14601", "Doação Financeira a Partidos e Candidatos"},
		Structs.DocumentCNJ{"14632", "14601", "Erros de Validação de Partes e Advogado"},
		Structs.DocumentCNJ{"14633", "14601", "Extrato da Prestação de Contas"},
		Structs.DocumentCNJ{"14634", "14601", "Notas Explicativas"},
		Structs.DocumentCNJ{"14635", "14601", "Origem de Recursos"},
		Structs.DocumentCNJ{"14636", "14601", "Petição de Encerramento de Reabertura"},
		Structs.DocumentCNJ{"14637", "14601", "Receita"},
		Structs.DocumentCNJ{"14638", "14601", "Relatório de Pendências"},
		Structs.DocumentCNJ{"14639", "14601", "Representante"},
		Structs.DocumentCNJ{"14640", "14601", "Sobras Campanha"},
		Structs.DocumentCNJ{"14641", "14601", "Transferência entre Conta Bancária"},
		Structs.DocumentCNJ{"14642", "3", "Registro de Candidatura"},
		Structs.DocumentCNJ{"14643", "14642", "Atas de Convenção"},
		Structs.DocumentCNJ{"14644", "14642", "Certidão Criminal da Justiça Estadual de 1º Grau"},
		Structs.DocumentCNJ{"14645", "14642", "Certidão Criminal da Justiça Estadual de 2º Grau"},
		Structs.DocumentCNJ{"14646", "14642", "Certidão Criminal da Justiça Federal de 1º Grau"},
		Structs.DocumentCNJ{"14647", "14642", "Certidão Criminal da Justiça Federal de 2º Grau"},
		Structs.DocumentCNJ{"14648", "14642", "Certidão Criminal de Foro por Prerrogativa de Função"},
		Structs.DocumentCNJ{"14649", "14642", "Declaração de Bens"},
		Structs.DocumentCNJ{"14650", "2", "Telegrama"},
		Structs.DocumentCNJ{"14651", "4", "Telegrama"},
		Structs.DocumentCNJ{"14652", "2", "Notas Taquigráficas"},
	)
	return DocumentCNJ
}
